[package]
name = "nte-dps-tool-tauri"
version = "0.4.3"
description = "Tauri desktop shell for NTE DPS TOOL"
authors = ["NTE DPS TOOL contributors"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/kongbaiz/nte-dps-toolkit"
edition = "2024"
rust-version = "1.98"
autobins = false

[lints.rust]
linker_messages = "allow"

[features]
default = []
external_resources = ["nte-dps-tool/external_resources"]

[lib]
name = "nte_dps_tool_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "nte-dps-tool"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-dialog = { version = "2.7.2", default-features = false }
tauri-plugin-log = "2"
tokio = { version = "1", features = ["time"] }
nte-dps-tool = { path = "..", default-features = false, features = ["desktop", "tauri_frontend"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
debug = false
