#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HTSharingActor

#include "Basic.hpp"

#include "HTAnimSharing_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HTSharingActor.BP_HTSharingActor_C
// 0x0000 (0x02D0 - 0x02D0)
class ABP_HTSharingActor_C final : public AHTSharingActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HTSharingActor_C">();
	}
	static class ABP_HTSharingActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HTSharingActor_C>();
	}
};
static_assert(alignof(ABP_HTSharingActor_C) == 0x000008, "Wrong alignment on ABP_HTSharingActor_C");
static_assert(sizeof(ABP_HTSharingActor_C) == 0x0002D0, "Wrong size on ABP_HTSharingActor_C");

}

