#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_CircleBar_Skill

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPUI_CircleBar_Skill.BPUI_CircleBar_Skill_C.ExecuteUbergraph_BPUI_CircleBar_Skill
// 0x0004 (0x0004 - 0x0000)
struct BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill) == 0x000004, "Wrong alignment on BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill");
static_assert(sizeof(BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill) == 0x000004, "Wrong size on BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill");
static_assert(offsetof(BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill, EntryPoint) == 0x000000, "Member 'BPUI_CircleBar_Skill_C_ExecuteUbergraph_BPUI_CircleBar_Skill::EntryPoint' has a wrong offset!");

}

