#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_SkillInput

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_SkillInput.BPUI_SkillInput_C
// 0x159DDE38 (0x159DF000 - 0x11C8)
class alignas(0x159DF000) UBPUI_SkillInput_C final : public UHTUI_SkillInput
{
public:
	uint8                                         Pad_11C8[0x8];                                     // 0x11C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x11D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Vx_Glow_Glow_1;                                    // 0x11D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             SlotMappablieKey;                                  // 0x11E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Fx_Glow_Charge_Yuan02_1;                     // 0x11E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Fx_Glow_Charge;                              // 0x11F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Bg;                                          // 0x11F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_111;                                         // 0x1200(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_48;                                          // 0x1208(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Dfde_E3;                                           // 0x1210(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Dfde_E2;                                           // 0x1218(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Dfde_E1;                                           // 0x1220(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Dfde_03;                                           // 0x1228(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Dfde_02;                                           // 0x1230(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Dfde_01;                                           // 0x1238(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSlateBrush                            Skill_Bg;                                          // 0x1240(0x00B0)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BPUI_SkillInput(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetSkillBg();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPUI_SkillInput_C">();
	}
	static class UBPUI_SkillInput_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_SkillInput_C>();
	}
};
static_assert(alignof(UBPUI_SkillInput_C) == 0x159DF000, "Wrong alignment on UBPUI_SkillInput_C");
static_assert(sizeof(UBPUI_SkillInput_C) == 0x159DF000, "Wrong size on UBPUI_SkillInput_C");
static_assert(offsetof(UBPUI_SkillInput_C, UberGraphFrame) == 0x0011D0, "Member 'UBPUI_SkillInput_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Vx_Glow_Glow_1) == 0x0011D8, "Member 'UBPUI_SkillInput_C::Vx_Glow_Glow_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, SlotMappablieKey) == 0x0011E0, "Member 'UBPUI_SkillInput_C::SlotMappablieKey' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Image_Fx_Glow_Charge_Yuan02_1) == 0x0011E8, "Member 'UBPUI_SkillInput_C::Image_Fx_Glow_Charge_Yuan02_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Image_Fx_Glow_Charge) == 0x0011F0, "Member 'UBPUI_SkillInput_C::Image_Fx_Glow_Charge' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Image_Bg) == 0x0011F8, "Member 'UBPUI_SkillInput_C::Image_Bg' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Image_111) == 0x001200, "Member 'UBPUI_SkillInput_C::Image_111' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Image_48) == 0x001208, "Member 'UBPUI_SkillInput_C::Image_48' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Dfde_E3) == 0x001210, "Member 'UBPUI_SkillInput_C::Dfde_E3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Dfde_E2) == 0x001218, "Member 'UBPUI_SkillInput_C::Dfde_E2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Dfde_E1) == 0x001220, "Member 'UBPUI_SkillInput_C::Dfde_E1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Dfde_03) == 0x001228, "Member 'UBPUI_SkillInput_C::Dfde_03' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Dfde_02) == 0x001230, "Member 'UBPUI_SkillInput_C::Dfde_02' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Dfde_01) == 0x001238, "Member 'UBPUI_SkillInput_C::Dfde_01' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_C, Skill_Bg) == 0x001240, "Member 'UBPUI_SkillInput_C::Skill_Bg' has a wrong offset!");

}

