#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_SkillInput_Ultra

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_SkillInput_Ultra.BPUI_SkillInput_Ultra_C
// 0x159DDAE0 (0x159DF000 - 0x1520)
#pragma pack(push, 0x1)
class alignas(0x159DF000) UBPUI_SkillInput_Ultra_C : public UHTUI_SkillInput_Ultra
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1520(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Vx_Version1_04;                                    // 0x1528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Version1_03;                                    // 0x1530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Version1_02;                                    // 0x1538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Version1_01;                                    // 0x1540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Switch1_1;                                      // 0x1548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Switch1;                                        // 0x1550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_5_1;                                       // 0x1558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_4_1;                                       // 0x1560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_3_1;                                       // 0x1568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_2_1;                                       // 0x1570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_1_1;                                       // 0x1578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan1;                                          // 0x1580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_5;                                         // 0x1588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_4;                                         // 0x1590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_3;                                         // 0x1598(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_2;                                         // 0x15A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan_1;                                         // 0x15A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_huan;                                           // 0x15B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow_Glow_1;                                    // 0x15B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow9_5;                                        // 0x15C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow9_4;                                        // 0x15C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow9_3;                                        // 0x15D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow9_2;                                        // 0x15D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow9_1;                                        // 0x15E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow9;                                          // 0x15E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow8_5;                                        // 0x15F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow8_4;                                        // 0x15F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow8_3;                                        // 0x1600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow8_2;                                        // 0x1608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow8_1;                                        // 0x1610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow8;                                          // 0x1618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow7_5;                                        // 0x1620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow7_4;                                        // 0x1628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow7_3;                                        // 0x1630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow7_2;                                        // 0x1638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow7_1;                                        // 0x1640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow7;                                          // 0x1648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow6_5;                                        // 0x1650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow6_4;                                        // 0x1658(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow6_3;                                        // 0x1660(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow6_2;                                        // 0x1668(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow6_1;                                        // 0x1670(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow6;                                          // 0x1678(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow5_5;                                        // 0x1680(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow5_4;                                        // 0x1688(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow5_3;                                        // 0x1690(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow5_2;                                        // 0x1698(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow5_1;                                        // 0x16A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow5;                                          // 0x16A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow4_5;                                        // 0x16B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow4_4;                                        // 0x16B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow4_3;                                        // 0x16C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow4_2;                                        // 0x16C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow4_1;                                        // 0x16D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow4;                                          // 0x16D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow3_Film;                                     // 0x16E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow3_5;                                        // 0x16E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow3_4;                                        // 0x16F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow3_2;                                        // 0x16F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow3_1;                                        // 0x1700(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow3;                                          // 0x1708(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow2_1;                                        // 0x1710(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow2;                                          // 0x1718(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16_Film;                                    // 0x1720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16_5;                                       // 0x1728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16_4;                                       // 0x1730(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16_3;                                       // 0x1738(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16_2;                                       // 0x1740(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16_1;                                       // 0x1748(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow16;                                         // 0x1750(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow15_5;                                       // 0x1758(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow15_4;                                       // 0x1760(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow15_3;                                       // 0x1768(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow15_2;                                       // 0x1770(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow15_1;                                       // 0x1778(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow15;                                         // 0x1780(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow14;                                         // 0x1788(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow13_1;                                       // 0x1790(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow13;                                         // 0x1798(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow12_1;                                       // 0x17A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow12;                                         // 0x17A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow11;                                         // 0x17B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow10;                                         // 0x17B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow1_5;                                        // 0x17C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow1_4;                                        // 0x17C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow1_3;                                        // 0x17D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow1_2;                                        // 0x17D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow1_1;                                        // 0x17E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow1;                                          // 0x17E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow_4;                                         // 0x17F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow_3;                                         // 0x17F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow_2;                                         // 0x1800(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow_1;                                         // 0x1808(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vx_Glow;                                           // 0x1810(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHTUIExtensionPointWidget*              SubEffect;                                         // 0x1818(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             SlotMappablieKey;                                  // 0x1820(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               OverlaySwitch;                                     // 0x1828(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               OverlayEnd;                                        // 0x1830(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               OverlayCharge;                                     // 0x1838(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlaybg;                                         // 0x1840(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_Film;                                            // 0x1848(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_6_1;                                             // 0x1850(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_5_1;                                             // 0x1858(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_4_1;                                             // 0x1860(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_3_1;                                             // 0x1868(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_2_1;                                             // 0x1870(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_1_1;                                             // 0x1878(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_6;                                               // 0x1880(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_5;                                               // 0x1888(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_4;                                               // 0x1890(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_3;                                               // 0x1898(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_2;                                               // 0x18A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNiagaraSystemWidget*                   N_1;                                               // 0x18A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Fx_Glow_Charge_Yuan02_1;                     // 0x18B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Fx_Glow_Charge;                              // 0x18B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_bg4_1;                                       // 0x18C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_bg4;                                         // 0x18C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_bg3_001;                                     // 0x18D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_bg3_1;                                       // 0x18D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_bg3;                                         // 0x18E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BG1_1;                                       // 0x18E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BG1;                                         // 0x18F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Bg;                                          // 0x18F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_08;                                         // 0x1900(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_06;                                         // 0x1908(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_05;                                         // 0x1910(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_04;                                         // 0x1918(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_03;                                         // 0x1920(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_02;                                         // 0x1928(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_01;                                         // 0x1930(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_7;                                          // 0x1938(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_6;                                          // 0x1940(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_5;                                          // 0x1948(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_2;                                          // 0x1950(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Film_1_1;                                          // 0x1958(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 click5;                                            // 0x1960(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 click3_1;                                          // 0x1968(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 click2;                                            // 0x1970(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 click1;                                            // 0x1978(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ChargeProgressBarElement_1;                        // 0x1980(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       ChargeHitAnim_Mask;                                // 0x1988(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ClickAnim_Xun_Loop;                                // 0x1990(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1998[0x8];                                     // 0x1998(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            Skill_Bg;                                          // 0x19A0(0x00B0)(Edit, BlueprintVisible)
	struct FLinearColor                           In_Color_and_Opacity;                              // 0x1A50(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_SkillInputBtnColorAndOpacity(bool bIsColorAndOpacity);
	void ExecuteUbergraph_BPUI_SkillInput_Ultra(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SequenceEvent();
	void SequenceEvent_0();
	void SequenceEvent_1();
	void SequenceEvent_10();
	void SequenceEvent_11();
	void SequenceEvent_12();
	void SequenceEvent_13();
	void SequenceEvent_2();
	void SequenceEvent_3();
	void SequenceEvent_4();
	void SequenceEvent_5();
	void SequenceEvent_6();
	void SequenceEvent_7();
	void SequenceEvent_8();
	void SequenceEvent_9();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_0();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_1();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_10();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_11();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_12();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_13();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_14();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_2();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_3();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_4();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_5();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_6();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_7();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_8();
	void SequenceEvent__ENTRYPOINTBPUI_SkillInput_Ultra_9();
	void SetSkillBg();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPUI_SkillInput_Ultra_C">();
	}
	static class UBPUI_SkillInput_Ultra_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_SkillInput_Ultra_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(UBPUI_SkillInput_Ultra_C) == 0x159DF000, "Wrong alignment on UBPUI_SkillInput_Ultra_C");
static_assert(sizeof(UBPUI_SkillInput_Ultra_C) == 0x159DF000, "Wrong size on UBPUI_SkillInput_Ultra_C");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, UberGraphFrame) == 0x001520, "Member 'UBPUI_SkillInput_Ultra_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Version1_04) == 0x001528, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Version1_04' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Version1_03) == 0x001530, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Version1_03' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Version1_02) == 0x001538, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Version1_02' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Version1_01) == 0x001540, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Version1_01' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Switch1_1) == 0x001548, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Switch1_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Switch1) == 0x001550, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Switch1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_5_1) == 0x001558, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_5_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_4_1) == 0x001560, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_4_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_3_1) == 0x001568, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_3_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_2_1) == 0x001570, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_2_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_1_1) == 0x001578, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_1_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan1) == 0x001580, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_5) == 0x001588, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_4) == 0x001590, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_3) == 0x001598, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_2) == 0x0015A0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan_1) == 0x0015A8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_huan) == 0x0015B0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_huan' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow_Glow_1) == 0x0015B8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow_Glow_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow9_5) == 0x0015C0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow9_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow9_4) == 0x0015C8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow9_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow9_3) == 0x0015D0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow9_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow9_2) == 0x0015D8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow9_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow9_1) == 0x0015E0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow9_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow9) == 0x0015E8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow9' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow8_5) == 0x0015F0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow8_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow8_4) == 0x0015F8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow8_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow8_3) == 0x001600, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow8_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow8_2) == 0x001608, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow8_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow8_1) == 0x001610, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow8_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow8) == 0x001618, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow8' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow7_5) == 0x001620, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow7_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow7_4) == 0x001628, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow7_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow7_3) == 0x001630, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow7_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow7_2) == 0x001638, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow7_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow7_1) == 0x001640, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow7_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow7) == 0x001648, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow7' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow6_5) == 0x001650, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow6_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow6_4) == 0x001658, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow6_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow6_3) == 0x001660, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow6_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow6_2) == 0x001668, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow6_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow6_1) == 0x001670, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow6_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow6) == 0x001678, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow6' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow5_5) == 0x001680, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow5_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow5_4) == 0x001688, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow5_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow5_3) == 0x001690, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow5_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow5_2) == 0x001698, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow5_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow5_1) == 0x0016A0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow5_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow5) == 0x0016A8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow4_5) == 0x0016B0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow4_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow4_4) == 0x0016B8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow4_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow4_3) == 0x0016C0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow4_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow4_2) == 0x0016C8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow4_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow4_1) == 0x0016D0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow4_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow4) == 0x0016D8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow3_Film) == 0x0016E0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow3_Film' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow3_5) == 0x0016E8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow3_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow3_4) == 0x0016F0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow3_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow3_2) == 0x0016F8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow3_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow3_1) == 0x001700, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow3_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow3) == 0x001708, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow2_1) == 0x001710, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow2_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow2) == 0x001718, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16_Film) == 0x001720, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16_Film' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16_5) == 0x001728, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16_4) == 0x001730, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16_3) == 0x001738, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16_2) == 0x001740, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16_1) == 0x001748, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow16) == 0x001750, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow16' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow15_5) == 0x001758, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow15_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow15_4) == 0x001760, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow15_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow15_3) == 0x001768, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow15_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow15_2) == 0x001770, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow15_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow15_1) == 0x001778, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow15_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow15) == 0x001780, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow15' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow14) == 0x001788, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow14' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow13_1) == 0x001790, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow13_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow13) == 0x001798, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow13' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow12_1) == 0x0017A0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow12_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow12) == 0x0017A8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow12' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow11) == 0x0017B0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow11' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow10) == 0x0017B8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow10' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow1_5) == 0x0017C0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow1_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow1_4) == 0x0017C8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow1_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow1_3) == 0x0017D0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow1_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow1_2) == 0x0017D8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow1_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow1_1) == 0x0017E0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow1_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow1) == 0x0017E8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow_4) == 0x0017F0, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow_3) == 0x0017F8, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow_2) == 0x001800, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow_1) == 0x001808, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Vx_Glow) == 0x001810, "Member 'UBPUI_SkillInput_Ultra_C::Vx_Glow' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, SubEffect) == 0x001818, "Member 'UBPUI_SkillInput_Ultra_C::SubEffect' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, SlotMappablieKey) == 0x001820, "Member 'UBPUI_SkillInput_Ultra_C::SlotMappablieKey' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, OverlaySwitch) == 0x001828, "Member 'UBPUI_SkillInput_Ultra_C::OverlaySwitch' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, OverlayEnd) == 0x001830, "Member 'UBPUI_SkillInput_Ultra_C::OverlayEnd' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, OverlayCharge) == 0x001838, "Member 'UBPUI_SkillInput_Ultra_C::OverlayCharge' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Overlaybg) == 0x001840, "Member 'UBPUI_SkillInput_Ultra_C::Overlaybg' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_Film) == 0x001848, "Member 'UBPUI_SkillInput_Ultra_C::N_Film' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_6_1) == 0x001850, "Member 'UBPUI_SkillInput_Ultra_C::N_6_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_5_1) == 0x001858, "Member 'UBPUI_SkillInput_Ultra_C::N_5_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_4_1) == 0x001860, "Member 'UBPUI_SkillInput_Ultra_C::N_4_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_3_1) == 0x001868, "Member 'UBPUI_SkillInput_Ultra_C::N_3_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_2_1) == 0x001870, "Member 'UBPUI_SkillInput_Ultra_C::N_2_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_1_1) == 0x001878, "Member 'UBPUI_SkillInput_Ultra_C::N_1_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_6) == 0x001880, "Member 'UBPUI_SkillInput_Ultra_C::N_6' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_5) == 0x001888, "Member 'UBPUI_SkillInput_Ultra_C::N_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_4) == 0x001890, "Member 'UBPUI_SkillInput_Ultra_C::N_4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_3) == 0x001898, "Member 'UBPUI_SkillInput_Ultra_C::N_3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_2) == 0x0018A0, "Member 'UBPUI_SkillInput_Ultra_C::N_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, N_1) == 0x0018A8, "Member 'UBPUI_SkillInput_Ultra_C::N_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_Fx_Glow_Charge_Yuan02_1) == 0x0018B0, "Member 'UBPUI_SkillInput_Ultra_C::Image_Fx_Glow_Charge_Yuan02_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_Fx_Glow_Charge) == 0x0018B8, "Member 'UBPUI_SkillInput_Ultra_C::Image_Fx_Glow_Charge' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_bg4_1) == 0x0018C0, "Member 'UBPUI_SkillInput_Ultra_C::Image_bg4_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_bg4) == 0x0018C8, "Member 'UBPUI_SkillInput_Ultra_C::Image_bg4' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_bg3_001) == 0x0018D0, "Member 'UBPUI_SkillInput_Ultra_C::Image_bg3_001' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_bg3_1) == 0x0018D8, "Member 'UBPUI_SkillInput_Ultra_C::Image_bg3_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_bg3) == 0x0018E0, "Member 'UBPUI_SkillInput_Ultra_C::Image_bg3' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_BG1_1) == 0x0018E8, "Member 'UBPUI_SkillInput_Ultra_C::Image_BG1_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_BG1) == 0x0018F0, "Member 'UBPUI_SkillInput_Ultra_C::Image_BG1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Image_Bg) == 0x0018F8, "Member 'UBPUI_SkillInput_Ultra_C::Image_Bg' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_08) == 0x001900, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_08' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_06) == 0x001908, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_06' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_05) == 0x001910, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_05' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_04) == 0x001918, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_04' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_03) == 0x001920, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_03' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_02) == 0x001928, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_02' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_01) == 0x001930, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_01' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_7) == 0x001938, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_7' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_6) == 0x001940, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_6' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_5) == 0x001948, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_2) == 0x001950, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Film_1_1) == 0x001958, "Member 'UBPUI_SkillInput_Ultra_C::Film_1_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, click5) == 0x001960, "Member 'UBPUI_SkillInput_Ultra_C::click5' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, click3_1) == 0x001968, "Member 'UBPUI_SkillInput_Ultra_C::click3_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, click2) == 0x001970, "Member 'UBPUI_SkillInput_Ultra_C::click2' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, click1) == 0x001978, "Member 'UBPUI_SkillInput_Ultra_C::click1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, ChargeProgressBarElement_1) == 0x001980, "Member 'UBPUI_SkillInput_Ultra_C::ChargeProgressBarElement_1' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, ChargeHitAnim_Mask) == 0x001988, "Member 'UBPUI_SkillInput_Ultra_C::ChargeHitAnim_Mask' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, ClickAnim_Xun_Loop) == 0x001990, "Member 'UBPUI_SkillInput_Ultra_C::ClickAnim_Xun_Loop' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, Skill_Bg) == 0x0019A0, "Member 'UBPUI_SkillInput_Ultra_C::Skill_Bg' has a wrong offset!");
static_assert(offsetof(UBPUI_SkillInput_Ultra_C, In_Color_and_Opacity) == 0x001A50, "Member 'UBPUI_SkillInput_Ultra_C::In_Color_and_Opacity' has a wrong offset!");

}

