#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Empty

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Empty.ButtonStyle-Empty_C
// 0x0000 (0x0710 - 0x0710)
class UButtonStyle_Empty_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Empty_C">();
	}
	static class UButtonStyle_Empty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Empty_C>();
	}
};
static_assert(alignof(UButtonStyle_Empty_C) == 0x000008, "Wrong alignment on UButtonStyle_Empty_C");
static_assert(sizeof(UButtonStyle_Empty_C) == 0x000710, "Wrong size on UButtonStyle_Empty_C");

}

