#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ElectraProtronFactory

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class ElectraProtronFactory.ElectraProtronFactorySettings
// 0x0008 (0x0030 - 0x0028)
class UElectraProtronFactorySettings final : public UObject
{
public:
	bool                                          bPreferProtronInEditor;                            // 0x0028(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPreferProtronInGame;                              // 0x0029(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ElectraProtronFactorySettings">();
	}
	static class UElectraProtronFactorySettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UElectraProtronFactorySettings>();
	}
};
static_assert(alignof(UElectraProtronFactorySettings) == 0x000008, "Wrong alignment on UElectraProtronFactorySettings");
static_assert(sizeof(UElectraProtronFactorySettings) == 0x000030, "Wrong size on UElectraProtronFactorySettings");
static_assert(offsetof(UElectraProtronFactorySettings, bPreferProtronInEditor) == 0x000028, "Member 'UElectraProtronFactorySettings::bPreferProtronInEditor' has a wrong offset!");
static_assert(offsetof(UElectraProtronFactorySettings, bPreferProtronInGame) == 0x000029, "Member 'UElectraProtronFactorySettings::bPreferProtronInGame' has a wrong offset!");

}

