#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginPlayerAnimBlueprint_Male

#include "Basic.hpp"

#include "LoginPlayerAnimBlueprint_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass LoginPlayerAnimBlueprint_Male.LoginPlayerAnimBlueprint_Male_C
// 0x0000 (0x05E8 - 0x05E8)
class ULoginPlayerAnimBlueprint_Male_C final : public ULoginPlayerAnimBlueprint_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LoginPlayerAnimBlueprint_Male_C">();
	}
	static class ULoginPlayerAnimBlueprint_Male_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoginPlayerAnimBlueprint_Male_C>();
	}
};
static_assert(alignof(ULoginPlayerAnimBlueprint_Male_C) == 0x000008, "Wrong alignment on ULoginPlayerAnimBlueprint_Male_C");
static_assert(sizeof(ULoginPlayerAnimBlueprint_Male_C) == 0x0005E8, "Wrong size on ULoginPlayerAnimBlueprint_Male_C");

}

