#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MassAIDebug

#include "Basic.hpp"

#include "MassEntity_classes.hpp"


namespace SDK
{

// Class MassAIDebug.MassDebugStateTreeProcessor
// 0x0350 (0x0410 - 0x00C0)
class UMassDebugStateTreeProcessor final : public UMassProcessor
{
public:
	uint8                                         Pad_C0[0x350];                                     // 0x00C0(0x0350)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MassDebugStateTreeProcessor">();
	}
	static class UMassDebugStateTreeProcessor* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMassDebugStateTreeProcessor>();
	}
};
static_assert(alignof(UMassDebugStateTreeProcessor) == 0x000008, "Wrong alignment on UMassDebugStateTreeProcessor");
static_assert(sizeof(UMassDebugStateTreeProcessor) == 0x000410, "Wrong size on UMassDebugStateTreeProcessor");

}

