#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewBlueprint_queue

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NewBlueprint_queue.NewBlueprint_queue_C
// 0x0000 (0x0370 - 0x0370)
class UNewBlueprint_queue_C final : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NewBlueprint_queue_C">();
	}
	static class UNewBlueprint_queue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNewBlueprint_queue_C>();
	}
};
static_assert(alignof(UNewBlueprint_queue_C) == 0x000008, "Wrong alignment on UNewBlueprint_queue_C");
static_assert(sizeof(UNewBlueprint_queue_C) == 0x000370, "Wrong size on UNewBlueprint_queue_C");

}

