#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PointCloud

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PointCloud_structs.hpp"


namespace SDK::Params
{

// Function PointCloud.PointCloud.LoadFromPoints
// 0x0018 (0x0018 - 0x0000)
struct PointCloud_LoadFromPoints final
{
public:
	TArray<struct FPointCloudPoint>               InPoints;                                          // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_LoadFromPoints) == 0x000008, "Wrong alignment on PointCloud_LoadFromPoints");
static_assert(sizeof(PointCloud_LoadFromPoints) == 0x000018, "Wrong size on PointCloud_LoadFromPoints");
static_assert(offsetof(PointCloud_LoadFromPoints, InPoints) == 0x000000, "Member 'PointCloud_LoadFromPoints::InPoints' has a wrong offset!");
static_assert(offsetof(PointCloud_LoadFromPoints, ReturnValue) == 0x000010, "Member 'PointCloud_LoadFromPoints::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.MakeView
// 0x0008 (0x0008 - 0x0000)
struct PointCloud_MakeView final
{
public:
	class UPointCloudView*                        ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_MakeView) == 0x000008, "Wrong alignment on PointCloud_MakeView");
static_assert(sizeof(PointCloud_MakeView) == 0x000008, "Wrong size on PointCloud_MakeView");
static_assert(offsetof(PointCloud_MakeView, ReturnValue) == 0x000000, "Member 'PointCloud_MakeView::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.Reimport
// 0x0040 (0x0040 - 0x0000)
struct PointCloud_Reimport final
{
public:
	struct FBox                                   ReimportBounds;                                    // 0x0000(0x0038)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0038(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_Reimport) == 0x000001, "Wrong alignment on PointCloud_Reimport");
static_assert(sizeof(PointCloud_Reimport) == 0x000040, "Wrong size on PointCloud_Reimport");
static_assert(offsetof(PointCloud_Reimport, ReimportBounds) == 0x000000, "Member 'PointCloud_Reimport::ReimportBounds' has a wrong offset!");
static_assert(offsetof(PointCloud_Reimport, ReturnValue) == 0x000038, "Member 'PointCloud_Reimport::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.ReplacePoints
// 0x0050 (0x0050 - 0x0000)
struct PointCloud_ReplacePoints final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBox                                   ReimportBounds;                                    // 0x0010(0x0038)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0048(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_ReplacePoints) == 0x000008, "Wrong alignment on PointCloud_ReplacePoints");
static_assert(sizeof(PointCloud_ReplacePoints) == 0x000050, "Wrong size on PointCloud_ReplacePoints");
static_assert(offsetof(PointCloud_ReplacePoints, Filename) == 0x000000, "Member 'PointCloud_ReplacePoints::Filename' has a wrong offset!");
static_assert(offsetof(PointCloud_ReplacePoints, ReimportBounds) == 0x000010, "Member 'PointCloud_ReplacePoints::ReimportBounds' has a wrong offset!");
static_assert(offsetof(PointCloud_ReplacePoints, ReturnValue) == 0x000048, "Member 'PointCloud_ReplacePoints::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.SaveToDisk
// 0x0018 (0x0018 - 0x0000)
struct PointCloud_SaveToDisk final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_SaveToDisk) == 0x000008, "Wrong alignment on PointCloud_SaveToDisk");
static_assert(sizeof(PointCloud_SaveToDisk) == 0x000018, "Wrong size on PointCloud_SaveToDisk");
static_assert(offsetof(PointCloud_SaveToDisk, Filename) == 0x000000, "Member 'PointCloud_SaveToDisk::Filename' has a wrong offset!");
static_assert(offsetof(PointCloud_SaveToDisk, ReturnValue) == 0x000010, "Member 'PointCloud_SaveToDisk::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.StartLogging
// 0x0018 (0x0018 - 0x0000)
struct PointCloud_StartLogging final
{
public:
	class FString                                 InFilename;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_StartLogging) == 0x000008, "Wrong alignment on PointCloud_StartLogging");
static_assert(sizeof(PointCloud_StartLogging) == 0x000018, "Wrong size on PointCloud_StartLogging");
static_assert(offsetof(PointCloud_StartLogging, InFilename) == 0x000000, "Member 'PointCloud_StartLogging::InFilename' has a wrong offset!");
static_assert(offsetof(PointCloud_StartLogging, ReturnValue) == 0x000010, "Member 'PointCloud_StartLogging::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.StopLogging
// 0x0001 (0x0001 - 0x0000)
struct PointCloud_StopLogging final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_StopLogging) == 0x000001, "Wrong alignment on PointCloud_StopLogging");
static_assert(sizeof(PointCloud_StopLogging) == 0x000001, "Wrong size on PointCloud_StopLogging");
static_assert(offsetof(PointCloud_StopLogging, ReturnValue) == 0x000000, "Member 'PointCloud_StopLogging::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.GetBounds
// 0x0038 (0x0038 - 0x0000)
struct PointCloud_GetBounds final
{
public:
	struct FBox                                   ReturnValue;                                       // 0x0000(0x0038)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_GetBounds) == 0x000001, "Wrong alignment on PointCloud_GetBounds");
static_assert(sizeof(PointCloud_GetBounds) == 0x000038, "Wrong size on PointCloud_GetBounds");
static_assert(offsetof(PointCloud_GetBounds, ReturnValue) == 0x000000, "Member 'PointCloud_GetBounds::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.GetCount
// 0x0004 (0x0004 - 0x0000)
struct PointCloud_GetCount final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_GetCount) == 0x000004, "Wrong alignment on PointCloud_GetCount");
static_assert(sizeof(PointCloud_GetCount) == 0x000004, "Wrong size on PointCloud_GetCount");
static_assert(offsetof(PointCloud_GetCount, ReturnValue) == 0x000000, "Member 'PointCloud_GetCount::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.GetDefaultAttributes
// 0x0010 (0x0010 - 0x0000)
struct PointCloud_GetDefaultAttributes final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_GetDefaultAttributes) == 0x000008, "Wrong alignment on PointCloud_GetDefaultAttributes");
static_assert(sizeof(PointCloud_GetDefaultAttributes) == 0x000010, "Wrong size on PointCloud_GetDefaultAttributes");
static_assert(offsetof(PointCloud_GetDefaultAttributes, ReturnValue) == 0x000000, "Member 'PointCloud_GetDefaultAttributes::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.GetLoadedFiles
// 0x0010 (0x0010 - 0x0000)
struct PointCloud_GetLoadedFiles final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_GetLoadedFiles) == 0x000008, "Wrong alignment on PointCloud_GetLoadedFiles");
static_assert(sizeof(PointCloud_GetLoadedFiles) == 0x000010, "Wrong size on PointCloud_GetLoadedFiles");
static_assert(offsetof(PointCloud_GetLoadedFiles, ReturnValue) == 0x000000, "Member 'PointCloud_GetLoadedFiles::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.GetMetadataAttributes
// 0x0050 (0x0050 - 0x0000)
struct PointCloud_GetMetadataAttributes final
{
public:
	TSet<class FString>                           ReturnValue;                                       // 0x0000(0x0050)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_GetMetadataAttributes) == 0x000008, "Wrong alignment on PointCloud_GetMetadataAttributes");
static_assert(sizeof(PointCloud_GetMetadataAttributes) == 0x000050, "Wrong size on PointCloud_GetMetadataAttributes");
static_assert(offsetof(PointCloud_GetMetadataAttributes, ReturnValue) == 0x000000, "Member 'PointCloud_GetMetadataAttributes::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.HasDefaultAttribute
// 0x0018 (0x0018 - 0x0000)
struct PointCloud_HasDefaultAttribute final
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_HasDefaultAttribute) == 0x000008, "Wrong alignment on PointCloud_HasDefaultAttribute");
static_assert(sizeof(PointCloud_HasDefaultAttribute) == 0x000018, "Wrong size on PointCloud_HasDefaultAttribute");
static_assert(offsetof(PointCloud_HasDefaultAttribute, Name_0) == 0x000000, "Member 'PointCloud_HasDefaultAttribute::Name_0' has a wrong offset!");
static_assert(offsetof(PointCloud_HasDefaultAttribute, ReturnValue) == 0x000010, "Member 'PointCloud_HasDefaultAttribute::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.HasMetaDataAttribute
// 0x0018 (0x0018 - 0x0000)
struct PointCloud_HasMetaDataAttribute final
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloud_HasMetaDataAttribute) == 0x000008, "Wrong alignment on PointCloud_HasMetaDataAttribute");
static_assert(sizeof(PointCloud_HasMetaDataAttribute) == 0x000018, "Wrong size on PointCloud_HasMetaDataAttribute");
static_assert(offsetof(PointCloud_HasMetaDataAttribute, Name_0) == 0x000000, "Member 'PointCloud_HasMetaDataAttribute::Name_0' has a wrong offset!");
static_assert(offsetof(PointCloud_HasMetaDataAttribute, ReturnValue) == 0x000010, "Member 'PointCloud_HasMetaDataAttribute::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloud.LoggingEnabled
// 0x0001 (0x0001 - 0x0000)
struct PointCloud_LoggingEnabled final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloud_LoggingEnabled) == 0x000001, "Wrong alignment on PointCloud_LoggingEnabled");
static_assert(sizeof(PointCloud_LoggingEnabled) == 0x000001, "Wrong size on PointCloud_LoggingEnabled");
static_assert(offsetof(PointCloud_LoggingEnabled, ReturnValue) == 0x000000, "Member 'PointCloud_LoggingEnabled::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceMapping.ClearManagedActors
// 0x0001 (0x0001 - 0x0000)
struct SliceAndDiceMapping_ClearManagedActors final
{
public:
	bool                                          bClearDisabled;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceMapping_ClearManagedActors) == 0x000001, "Wrong alignment on SliceAndDiceMapping_ClearManagedActors");
static_assert(sizeof(SliceAndDiceMapping_ClearManagedActors) == 0x000001, "Wrong size on SliceAndDiceMapping_ClearManagedActors");
static_assert(offsetof(SliceAndDiceMapping_ClearManagedActors, bClearDisabled) == 0x000000, "Member 'SliceAndDiceMapping_ClearManagedActors::bClearDisabled' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.CreateSliceAndDiceManager
// 0x0010 (0x0010 - 0x0000)
struct SliceAndDiceManager_CreateSliceAndDiceManager final
{
public:
	class UWorld*                                 InWorld;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASliceAndDiceManager*                   ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_CreateSliceAndDiceManager) == 0x000008, "Wrong alignment on SliceAndDiceManager_CreateSliceAndDiceManager");
static_assert(sizeof(SliceAndDiceManager_CreateSliceAndDiceManager) == 0x000010, "Wrong size on SliceAndDiceManager_CreateSliceAndDiceManager");
static_assert(offsetof(SliceAndDiceManager_CreateSliceAndDiceManager, InWorld) == 0x000000, "Member 'SliceAndDiceManager_CreateSliceAndDiceManager::InWorld' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_CreateSliceAndDiceManager, ReturnValue) == 0x000008, "Member 'SliceAndDiceManager_CreateSliceAndDiceManager::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.GetSliceAndDiceManagers
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_GetSliceAndDiceManagers final
{
public:
	class UWorld*                                 InWorld;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class ASliceAndDiceManager*>           ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_GetSliceAndDiceManagers) == 0x000008, "Wrong alignment on SliceAndDiceManager_GetSliceAndDiceManagers");
static_assert(sizeof(SliceAndDiceManager_GetSliceAndDiceManagers) == 0x000018, "Wrong size on SliceAndDiceManager_GetSliceAndDiceManagers");
static_assert(offsetof(SliceAndDiceManager_GetSliceAndDiceManagers, InWorld) == 0x000000, "Member 'SliceAndDiceManager_GetSliceAndDiceManagers::InWorld' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_GetSliceAndDiceManagers, ReturnValue) == 0x000008, "Member 'SliceAndDiceManager_GetSliceAndDiceManagers::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.GetSliceAndDiceManagersInLevel
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_GetSliceAndDiceManagersInLevel final
{
public:
	class ULevel*                                 InLevel;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class ASliceAndDiceManager*>           ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_GetSliceAndDiceManagersInLevel) == 0x000008, "Wrong alignment on SliceAndDiceManager_GetSliceAndDiceManagersInLevel");
static_assert(sizeof(SliceAndDiceManager_GetSliceAndDiceManagersInLevel) == 0x000018, "Wrong size on SliceAndDiceManager_GetSliceAndDiceManagersInLevel");
static_assert(offsetof(SliceAndDiceManager_GetSliceAndDiceManagersInLevel, InLevel) == 0x000000, "Member 'SliceAndDiceManager_GetSliceAndDiceManagersInLevel::InLevel' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_GetSliceAndDiceManagersInLevel, ReturnValue) == 0x000008, "Member 'SliceAndDiceManager_GetSliceAndDiceManagersInLevel::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.AddNewMapping
// 0x0008 (0x0008 - 0x0000)
struct SliceAndDiceManager_AddNewMapping final
{
public:
	class USliceAndDiceMapping*                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_AddNewMapping) == 0x000008, "Wrong alignment on SliceAndDiceManager_AddNewMapping");
static_assert(sizeof(SliceAndDiceManager_AddNewMapping) == 0x000008, "Wrong size on SliceAndDiceManager_AddNewMapping");
static_assert(offsetof(SliceAndDiceManager_AddNewMapping, ReturnValue) == 0x000000, "Member 'SliceAndDiceManager_AddNewMapping::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.DeleteAllManagedActors
// 0x0002 (0x0002 - 0x0000)
struct SliceAndDiceManager_DeleteAllManagedActors final
{
public:
	bool                                          bCleanDisabled;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_DeleteAllManagedActors) == 0x000001, "Wrong alignment on SliceAndDiceManager_DeleteAllManagedActors");
static_assert(sizeof(SliceAndDiceManager_DeleteAllManagedActors) == 0x000002, "Wrong size on SliceAndDiceManager_DeleteAllManagedActors");
static_assert(offsetof(SliceAndDiceManager_DeleteAllManagedActors, bCleanDisabled) == 0x000000, "Member 'SliceAndDiceManager_DeleteAllManagedActors::bCleanDisabled' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_DeleteAllManagedActors, ReturnValue) == 0x000001, "Member 'SliceAndDiceManager_DeleteAllManagedActors::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.DeleteManagedActorsFromMapping
// 0x0010 (0x0010 - 0x0000)
struct SliceAndDiceManager_DeleteManagedActorsFromMapping final
{
public:
	class USliceAndDiceMapping*                   InMapping;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCleanDisabled;                                    // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0009(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_DeleteManagedActorsFromMapping) == 0x000008, "Wrong alignment on SliceAndDiceManager_DeleteManagedActorsFromMapping");
static_assert(sizeof(SliceAndDiceManager_DeleteManagedActorsFromMapping) == 0x000010, "Wrong size on SliceAndDiceManager_DeleteManagedActorsFromMapping");
static_assert(offsetof(SliceAndDiceManager_DeleteManagedActorsFromMapping, InMapping) == 0x000000, "Member 'SliceAndDiceManager_DeleteManagedActorsFromMapping::InMapping' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_DeleteManagedActorsFromMapping, bCleanDisabled) == 0x000008, "Member 'SliceAndDiceManager_DeleteManagedActorsFromMapping::bCleanDisabled' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_DeleteManagedActorsFromMapping, ReturnValue) == 0x000009, "Member 'SliceAndDiceManager_DeleteManagedActorsFromMapping::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.DeleteManagedActorsFromMappings
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_DeleteManagedActorsFromMappings final
{
public:
	TArray<class USliceAndDiceMapping*>           InMappings;                                        // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          bCleanDisabled;                                    // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0011(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_DeleteManagedActorsFromMappings) == 0x000008, "Wrong alignment on SliceAndDiceManager_DeleteManagedActorsFromMappings");
static_assert(sizeof(SliceAndDiceManager_DeleteManagedActorsFromMappings) == 0x000018, "Wrong size on SliceAndDiceManager_DeleteManagedActorsFromMappings");
static_assert(offsetof(SliceAndDiceManager_DeleteManagedActorsFromMappings, InMappings) == 0x000000, "Member 'SliceAndDiceManager_DeleteManagedActorsFromMappings::InMappings' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_DeleteManagedActorsFromMappings, bCleanDisabled) == 0x000010, "Member 'SliceAndDiceManager_DeleteManagedActorsFromMappings::bCleanDisabled' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_DeleteManagedActorsFromMappings, ReturnValue) == 0x000011, "Member 'SliceAndDiceManager_DeleteManagedActorsFromMappings::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.FindMapping
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_FindMapping final
{
public:
	class UPointCloud*                            InPointCloud;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPointCloudSliceAndDiceRuleSet*         InRuleSet;                                         // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USliceAndDiceMapping*                   ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_FindMapping) == 0x000008, "Wrong alignment on SliceAndDiceManager_FindMapping");
static_assert(sizeof(SliceAndDiceManager_FindMapping) == 0x000018, "Wrong size on SliceAndDiceManager_FindMapping");
static_assert(offsetof(SliceAndDiceManager_FindMapping, InPointCloud) == 0x000000, "Member 'SliceAndDiceManager_FindMapping::InPointCloud' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_FindMapping, InRuleSet) == 0x000008, "Member 'SliceAndDiceManager_FindMapping::InRuleSet' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_FindMapping, ReturnValue) == 0x000010, "Member 'SliceAndDiceManager_FindMapping::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.FindOrAddMapping
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_FindOrAddMapping final
{
public:
	class UPointCloud*                            InPointCloud;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPointCloudSliceAndDiceRuleSet*         InRuleSet;                                         // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USliceAndDiceMapping*                   ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_FindOrAddMapping) == 0x000008, "Wrong alignment on SliceAndDiceManager_FindOrAddMapping");
static_assert(sizeof(SliceAndDiceManager_FindOrAddMapping) == 0x000018, "Wrong size on SliceAndDiceManager_FindOrAddMapping");
static_assert(offsetof(SliceAndDiceManager_FindOrAddMapping, InPointCloud) == 0x000000, "Member 'SliceAndDiceManager_FindOrAddMapping::InPointCloud' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_FindOrAddMapping, InRuleSet) == 0x000008, "Member 'SliceAndDiceManager_FindOrAddMapping::InRuleSet' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_FindOrAddMapping, ReturnValue) == 0x000010, "Member 'SliceAndDiceManager_FindOrAddMapping::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.MoveMapping
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_MoveMapping final
{
public:
	class USliceAndDiceMapping*                   InMapping;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ASliceAndDiceManager*                   InTargetManager;                                   // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_MoveMapping) == 0x000008, "Wrong alignment on SliceAndDiceManager_MoveMapping");
static_assert(sizeof(SliceAndDiceManager_MoveMapping) == 0x000018, "Wrong size on SliceAndDiceManager_MoveMapping");
static_assert(offsetof(SliceAndDiceManager_MoveMapping, InMapping) == 0x000000, "Member 'SliceAndDiceManager_MoveMapping::InMapping' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_MoveMapping, InTargetManager) == 0x000008, "Member 'SliceAndDiceManager_MoveMapping::InTargetManager' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_MoveMapping, ReturnValue) == 0x000010, "Member 'SliceAndDiceManager_MoveMapping::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.MoveMappings
// 0x0020 (0x0020 - 0x0000)
struct SliceAndDiceManager_MoveMappings final
{
public:
	TArray<class USliceAndDiceMapping*>           InMapping;                                         // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class ASliceAndDiceManager*                   InTargetManager;                                   // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_MoveMappings) == 0x000008, "Wrong alignment on SliceAndDiceManager_MoveMappings");
static_assert(sizeof(SliceAndDiceManager_MoveMappings) == 0x000020, "Wrong size on SliceAndDiceManager_MoveMappings");
static_assert(offsetof(SliceAndDiceManager_MoveMappings, InMapping) == 0x000000, "Member 'SliceAndDiceManager_MoveMappings::InMapping' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_MoveMappings, InTargetManager) == 0x000010, "Member 'SliceAndDiceManager_MoveMappings::InTargetManager' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_MoveMappings, ReturnValue) == 0x000018, "Member 'SliceAndDiceManager_MoveMappings::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.ReloadAllPointClouds
// 0x0001 (0x0001 - 0x0000)
struct SliceAndDiceManager_ReloadAllPointClouds final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_ReloadAllPointClouds) == 0x000001, "Wrong alignment on SliceAndDiceManager_ReloadAllPointClouds");
static_assert(sizeof(SliceAndDiceManager_ReloadAllPointClouds) == 0x000001, "Wrong size on SliceAndDiceManager_ReloadAllPointClouds");
static_assert(offsetof(SliceAndDiceManager_ReloadAllPointClouds, ReturnValue) == 0x000000, "Member 'SliceAndDiceManager_ReloadAllPointClouds::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.ReloadPointCloudsOnMappings
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_ReloadPointCloudsOnMappings final
{
public:
	TArray<class USliceAndDiceMapping*>           SelectedMappings;                                  // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_ReloadPointCloudsOnMappings) == 0x000008, "Wrong alignment on SliceAndDiceManager_ReloadPointCloudsOnMappings");
static_assert(sizeof(SliceAndDiceManager_ReloadPointCloudsOnMappings) == 0x000018, "Wrong size on SliceAndDiceManager_ReloadPointCloudsOnMappings");
static_assert(offsetof(SliceAndDiceManager_ReloadPointCloudsOnMappings, SelectedMappings) == 0x000000, "Member 'SliceAndDiceManager_ReloadPointCloudsOnMappings::SelectedMappings' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_ReloadPointCloudsOnMappings, ReturnValue) == 0x000010, "Member 'SliceAndDiceManager_ReloadPointCloudsOnMappings::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.RemoveMapping
// 0x0010 (0x0010 - 0x0000)
struct SliceAndDiceManager_RemoveMapping final
{
public:
	class USliceAndDiceMapping*                   InMapping;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeleteManagedActors;                              // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0009(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_RemoveMapping) == 0x000008, "Wrong alignment on SliceAndDiceManager_RemoveMapping");
static_assert(sizeof(SliceAndDiceManager_RemoveMapping) == 0x000010, "Wrong size on SliceAndDiceManager_RemoveMapping");
static_assert(offsetof(SliceAndDiceManager_RemoveMapping, InMapping) == 0x000000, "Member 'SliceAndDiceManager_RemoveMapping::InMapping' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_RemoveMapping, bDeleteManagedActors) == 0x000008, "Member 'SliceAndDiceManager_RemoveMapping::bDeleteManagedActors' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_RemoveMapping, ReturnValue) == 0x000009, "Member 'SliceAndDiceManager_RemoveMapping::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.RunReport
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_RunReport final
{
public:
	EPointCloudReportLevel                        Level;                                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_RunReport) == 0x000008, "Wrong alignment on SliceAndDiceManager_RunReport");
static_assert(sizeof(SliceAndDiceManager_RunReport) == 0x000018, "Wrong size on SliceAndDiceManager_RunReport");
static_assert(offsetof(SliceAndDiceManager_RunReport, Level) == 0x000000, "Member 'SliceAndDiceManager_RunReport::Level' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_RunReport, ReturnValue) == 0x000008, "Member 'SliceAndDiceManager_RunReport::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.RunReportOnMappings
// 0x0028 (0x0028 - 0x0000)
struct SliceAndDiceManager_RunReportOnMappings final
{
public:
	TArray<class USliceAndDiceMapping*>           SelectedMappings;                                  // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	EPointCloudReportLevel                        Level;                                             // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReturnValue;                                       // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_RunReportOnMappings) == 0x000008, "Wrong alignment on SliceAndDiceManager_RunReportOnMappings");
static_assert(sizeof(SliceAndDiceManager_RunReportOnMappings) == 0x000028, "Wrong size on SliceAndDiceManager_RunReportOnMappings");
static_assert(offsetof(SliceAndDiceManager_RunReportOnMappings, SelectedMappings) == 0x000000, "Member 'SliceAndDiceManager_RunReportOnMappings::SelectedMappings' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_RunReportOnMappings, Level) == 0x000010, "Member 'SliceAndDiceManager_RunReportOnMappings::Level' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_RunReportOnMappings, ReturnValue) == 0x000018, "Member 'SliceAndDiceManager_RunReportOnMappings::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.RunRules
// 0x0001 (0x0001 - 0x0000)
struct SliceAndDiceManager_RunRules final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_RunRules) == 0x000001, "Wrong alignment on SliceAndDiceManager_RunRules");
static_assert(sizeof(SliceAndDiceManager_RunRules) == 0x000001, "Wrong size on SliceAndDiceManager_RunRules");
static_assert(offsetof(SliceAndDiceManager_RunRules, ReturnValue) == 0x000000, "Member 'SliceAndDiceManager_RunRules::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.RunRulesOnMappings
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_RunRulesOnMappings final
{
public:
	TArray<class USliceAndDiceMapping*>           SelectedMappings;                                  // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(SliceAndDiceManager_RunRulesOnMappings) == 0x000008, "Wrong alignment on SliceAndDiceManager_RunRulesOnMappings");
static_assert(sizeof(SliceAndDiceManager_RunRulesOnMappings) == 0x000018, "Wrong size on SliceAndDiceManager_RunRulesOnMappings");
static_assert(offsetof(SliceAndDiceManager_RunRulesOnMappings, SelectedMappings) == 0x000000, "Member 'SliceAndDiceManager_RunRulesOnMappings::SelectedMappings' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_RunRulesOnMappings, ReturnValue) == 0x000010, "Member 'SliceAndDiceManager_RunRulesOnMappings::ReturnValue' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.SetLogging
// 0x0018 (0x0018 - 0x0000)
struct SliceAndDiceManager_SetLogging final
{
public:
	bool                                          bInLoggingEnabled;                                 // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 InLogPath;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_SetLogging) == 0x000008, "Wrong alignment on SliceAndDiceManager_SetLogging");
static_assert(sizeof(SliceAndDiceManager_SetLogging) == 0x000018, "Wrong size on SliceAndDiceManager_SetLogging");
static_assert(offsetof(SliceAndDiceManager_SetLogging, bInLoggingEnabled) == 0x000000, "Member 'SliceAndDiceManager_SetLogging::bInLoggingEnabled' has a wrong offset!");
static_assert(offsetof(SliceAndDiceManager_SetLogging, InLogPath) == 0x000008, "Member 'SliceAndDiceManager_SetLogging::InLogPath' has a wrong offset!");

// Function PointCloud.SliceAndDiceManager.NumMappings
// 0x0004 (0x0004 - 0x0000)
struct SliceAndDiceManager_NumMappings final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SliceAndDiceManager_NumMappings) == 0x000004, "Wrong alignment on SliceAndDiceManager_NumMappings");
static_assert(sizeof(SliceAndDiceManager_NumMappings) == 0x000004, "Wrong size on SliceAndDiceManager_NumMappings");
static_assert(offsetof(SliceAndDiceManager_NumMappings, ReturnValue) == 0x000000, "Member 'SliceAndDiceManager_NumMappings::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.AddRule
// 0x0018 (0x0018 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_AddRule final
{
public:
	class UPointCloudRule*                        InRule;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPointCloudRule*                        InParent;                                          // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InSlotIndex;                                       // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_AddRule) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_AddRule");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_AddRule) == 0x000018, "Wrong size on PointCloudSliceAndDiceRuleSet_AddRule");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_AddRule, InRule) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_AddRule::InRule' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_AddRule, InParent) == 0x000008, "Member 'PointCloudSliceAndDiceRuleSet_AddRule::InParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_AddRule, InSlotIndex) == 0x000010, "Member 'PointCloudSliceAndDiceRuleSet_AddRule::InSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_AddRule, ReturnValue) == 0x000014, "Member 'PointCloudSliceAndDiceRuleSet_AddRule::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.CopyRule
// 0x0018 (0x0018 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_CopyRule final
{
public:
	class UPointCloudRule*                        InRule;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPointCloudRule*                        InTargetParent;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InTargetSlotIndex;                                 // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_CopyRule) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_CopyRule");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_CopyRule) == 0x000018, "Wrong size on PointCloudSliceAndDiceRuleSet_CopyRule");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CopyRule, InRule) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_CopyRule::InRule' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CopyRule, InTargetParent) == 0x000008, "Member 'PointCloudSliceAndDiceRuleSet_CopyRule::InTargetParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CopyRule, InTargetSlotIndex) == 0x000010, "Member 'PointCloudSliceAndDiceRuleSet_CopyRule::InTargetSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CopyRule, ReturnValue) == 0x000014, "Member 'PointCloudSliceAndDiceRuleSet_CopyRule::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.CreateRule
// 0x0028 (0x0028 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_CreateRule final
{
public:
	class FString                                 RuleName;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPointCloudRule*                        ParentRule;                                        // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SlotIndex;                                         // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPointCloudRule*                        ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_CreateRule) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_CreateRule");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_CreateRule) == 0x000028, "Wrong size on PointCloudSliceAndDiceRuleSet_CreateRule");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CreateRule, RuleName) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_CreateRule::RuleName' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CreateRule, ParentRule) == 0x000010, "Member 'PointCloudSliceAndDiceRuleSet_CreateRule::ParentRule' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CreateRule, SlotIndex) == 0x000018, "Member 'PointCloudSliceAndDiceRuleSet_CreateRule::SlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_CreateRule, ReturnValue) == 0x000020, "Member 'PointCloudSliceAndDiceRuleSet_CreateRule::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.GetRules
// 0x0010 (0x0010 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_GetRules final
{
public:
	TArray<class UPointCloudRule*>                ReturnValue;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_GetRules) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_GetRules");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_GetRules) == 0x000010, "Wrong size on PointCloudSliceAndDiceRuleSet_GetRules");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_GetRules, ReturnValue) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_GetRules::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.MoveRule
// 0x0020 (0x0020 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_MoveRule final
{
public:
	class UPointCloudRule*                        InRuleParent;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InRuleSlotIndex;                                   // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPointCloudRule*                        InTargetParent;                                    // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InTargetSlotIndex;                                 // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x001C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_MoveRule) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_MoveRule");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_MoveRule) == 0x000020, "Wrong size on PointCloudSliceAndDiceRuleSet_MoveRule");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_MoveRule, InRuleParent) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_MoveRule::InRuleParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_MoveRule, InRuleSlotIndex) == 0x000008, "Member 'PointCloudSliceAndDiceRuleSet_MoveRule::InRuleSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_MoveRule, InTargetParent) == 0x000010, "Member 'PointCloudSliceAndDiceRuleSet_MoveRule::InTargetParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_MoveRule, InTargetSlotIndex) == 0x000018, "Member 'PointCloudSliceAndDiceRuleSet_MoveRule::InTargetSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_MoveRule, ReturnValue) == 0x00001C, "Member 'PointCloudSliceAndDiceRuleSet_MoveRule::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.RemoveRule
// 0x0018 (0x0018 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_RemoveRule final
{
public:
	class UPointCloudRule*                        InParent;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InSlotIndex;                                       // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPointCloudRule*                        ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_RemoveRule) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_RemoveRule");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_RemoveRule) == 0x000018, "Wrong size on PointCloudSliceAndDiceRuleSet_RemoveRule");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_RemoveRule, InParent) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_RemoveRule::InParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_RemoveRule, InSlotIndex) == 0x000008, "Member 'PointCloudSliceAndDiceRuleSet_RemoveRule::InSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_RemoveRule, ReturnValue) == 0x000010, "Member 'PointCloudSliceAndDiceRuleSet_RemoveRule::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudSliceAndDiceRuleSet.SwapRules
// 0x0020 (0x0020 - 0x0000)
struct PointCloudSliceAndDiceRuleSet_SwapRules final
{
public:
	class UPointCloudRule*                        InRuleParent;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InRuleSlotIndex;                                   // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPointCloudRule*                        InTargetParent;                                    // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InTargetSlotIndex;                                 // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x001C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudSliceAndDiceRuleSet_SwapRules) == 0x000008, "Wrong alignment on PointCloudSliceAndDiceRuleSet_SwapRules");
static_assert(sizeof(PointCloudSliceAndDiceRuleSet_SwapRules) == 0x000020, "Wrong size on PointCloudSliceAndDiceRuleSet_SwapRules");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_SwapRules, InRuleParent) == 0x000000, "Member 'PointCloudSliceAndDiceRuleSet_SwapRules::InRuleParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_SwapRules, InRuleSlotIndex) == 0x000008, "Member 'PointCloudSliceAndDiceRuleSet_SwapRules::InRuleSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_SwapRules, InTargetParent) == 0x000010, "Member 'PointCloudSliceAndDiceRuleSet_SwapRules::InTargetParent' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_SwapRules, InTargetSlotIndex) == 0x000018, "Member 'PointCloudSliceAndDiceRuleSet_SwapRules::InTargetSlotIndex' has a wrong offset!");
static_assert(offsetof(PointCloudSliceAndDiceRuleSet_SwapRules, ReturnValue) == 0x00001C, "Member 'PointCloudSliceAndDiceRuleSet_SwapRules::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnBoundingBox
// 0x0040 (0x0040 - 0x0000)
struct PointCloudView_FilterOnBoundingBox final
{
public:
	struct FBox                                   BoundingBox;                                       // 0x0000(0x0038)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInvertSelection;                                  // 0x0038(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0039(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnBoundingBox) == 0x000001, "Wrong alignment on PointCloudView_FilterOnBoundingBox");
static_assert(sizeof(PointCloudView_FilterOnBoundingBox) == 0x000040, "Wrong size on PointCloudView_FilterOnBoundingBox");
static_assert(offsetof(PointCloudView_FilterOnBoundingBox, BoundingBox) == 0x000000, "Member 'PointCloudView_FilterOnBoundingBox::BoundingBox' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnBoundingBox, bInvertSelection) == 0x000038, "Member 'PointCloudView_FilterOnBoundingBox::bInvertSelection' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnBoundingBox, Mode) == 0x000039, "Member 'PointCloudView_FilterOnBoundingBox::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnBoundingSphere
// 0x0020 (0x0020 - 0x0000)
struct PointCloudView_FilterOnBoundingSphere final
{
public:
	struct FVector                                Center;                                            // 0x0000(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Radius;                                            // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnBoundingSphere) == 0x000004, "Wrong alignment on PointCloudView_FilterOnBoundingSphere");
static_assert(sizeof(PointCloudView_FilterOnBoundingSphere) == 0x000020, "Wrong size on PointCloudView_FilterOnBoundingSphere");
static_assert(offsetof(PointCloudView_FilterOnBoundingSphere, Center) == 0x000000, "Member 'PointCloudView_FilterOnBoundingSphere::Center' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnBoundingSphere, Radius) == 0x000018, "Member 'PointCloudView_FilterOnBoundingSphere::Radius' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnBoundingSphere, Mode) == 0x00001C, "Member 'PointCloudView_FilterOnBoundingSphere::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnIndex
// 0x0008 (0x0008 - 0x0000)
struct PointCloudView_FilterOnIndex final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnIndex) == 0x000004, "Wrong alignment on PointCloudView_FilterOnIndex");
static_assert(sizeof(PointCloudView_FilterOnIndex) == 0x000008, "Wrong size on PointCloudView_FilterOnIndex");
static_assert(offsetof(PointCloudView_FilterOnIndex, Index_0) == 0x000000, "Member 'PointCloudView_FilterOnIndex::Index_0' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnIndex, Mode) == 0x000004, "Member 'PointCloudView_FilterOnIndex::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnMetadata
// 0x0028 (0x0028 - 0x0000)
struct PointCloudView_FilterOnMetadata final
{
public:
	class FString                                 MetaData;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Value;                                             // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnMetadata) == 0x000008, "Wrong alignment on PointCloudView_FilterOnMetadata");
static_assert(sizeof(PointCloudView_FilterOnMetadata) == 0x000028, "Wrong size on PointCloudView_FilterOnMetadata");
static_assert(offsetof(PointCloudView_FilterOnMetadata, MetaData) == 0x000000, "Member 'PointCloudView_FilterOnMetadata::MetaData' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnMetadata, Value) == 0x000010, "Member 'PointCloudView_FilterOnMetadata::Value' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnMetadata, Mode) == 0x000020, "Member 'PointCloudView_FilterOnMetadata::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnMetadataPattern
// 0x0028 (0x0028 - 0x0000)
struct PointCloudView_FilterOnMetadataPattern final
{
public:
	class FString                                 MetaData;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Pattern;                                           // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnMetadataPattern) == 0x000008, "Wrong alignment on PointCloudView_FilterOnMetadataPattern");
static_assert(sizeof(PointCloudView_FilterOnMetadataPattern) == 0x000028, "Wrong size on PointCloudView_FilterOnMetadataPattern");
static_assert(offsetof(PointCloudView_FilterOnMetadataPattern, MetaData) == 0x000000, "Member 'PointCloudView_FilterOnMetadataPattern::MetaData' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnMetadataPattern, Pattern) == 0x000010, "Member 'PointCloudView_FilterOnMetadataPattern::Pattern' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnMetadataPattern, Mode) == 0x000020, "Member 'PointCloudView_FilterOnMetadataPattern::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnOrientedBoundingBox
// 0x0070 (0x0070 - 0x0000)
struct PointCloudView_FilterOnOrientedBoundingBox final
{
public:
	struct FTransform                             InOBB;                                             // 0x0000(0x0060)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInvertSelection;                                  // 0x0060(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0061(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_62[0xE];                                       // 0x0062(0x000E)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnOrientedBoundingBox) == 0x000001, "Wrong alignment on PointCloudView_FilterOnOrientedBoundingBox");
static_assert(sizeof(PointCloudView_FilterOnOrientedBoundingBox) == 0x000070, "Wrong size on PointCloudView_FilterOnOrientedBoundingBox");
static_assert(offsetof(PointCloudView_FilterOnOrientedBoundingBox, InOBB) == 0x000000, "Member 'PointCloudView_FilterOnOrientedBoundingBox::InOBB' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnOrientedBoundingBox, bInvertSelection) == 0x000060, "Member 'PointCloudView_FilterOnOrientedBoundingBox::bInvertSelection' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnOrientedBoundingBox, Mode) == 0x000061, "Member 'PointCloudView_FilterOnOrientedBoundingBox::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnPointExpression
// 0x0018 (0x0018 - 0x0000)
struct PointCloudView_FilterOnPointExpression final
{
public:
	class FString                                 Expression;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnPointExpression) == 0x000008, "Wrong alignment on PointCloudView_FilterOnPointExpression");
static_assert(sizeof(PointCloudView_FilterOnPointExpression) == 0x000018, "Wrong size on PointCloudView_FilterOnPointExpression");
static_assert(offsetof(PointCloudView_FilterOnPointExpression, Expression) == 0x000000, "Member 'PointCloudView_FilterOnPointExpression::Expression' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnPointExpression, Mode) == 0x000010, "Member 'PointCloudView_FilterOnPointExpression::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnRange
// 0x000C (0x000C - 0x0000)
struct PointCloudView_FilterOnRange final
{
public:
	int32                                         StartIndex;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EndIndex;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnRange) == 0x000004, "Wrong alignment on PointCloudView_FilterOnRange");
static_assert(sizeof(PointCloudView_FilterOnRange) == 0x00000C, "Wrong size on PointCloudView_FilterOnRange");
static_assert(offsetof(PointCloudView_FilterOnRange, StartIndex) == 0x000000, "Member 'PointCloudView_FilterOnRange::StartIndex' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnRange, EndIndex) == 0x000004, "Member 'PointCloudView_FilterOnRange::EndIndex' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnRange, Mode) == 0x000008, "Member 'PointCloudView_FilterOnRange::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.FilterOnTile
// 0x0058 (0x0058 - 0x0000)
struct PointCloudView_FilterOnTile final
{
public:
	struct FBox                                   QueryGridBounds;                                   // 0x0000(0x0038)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InNumTilesX;                                       // 0x0038(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InNumTilesY;                                       // 0x003C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InNumTilesZ;                                       // 0x0040(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InTileX;                                           // 0x0044(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InTileY;                                           // 0x0048(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InTileZ;                                           // 0x004C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInvertSelection;                                  // 0x0050(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFilterMode                                   Mode;                                              // 0x0051(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_FilterOnTile) == 0x000004, "Wrong alignment on PointCloudView_FilterOnTile");
static_assert(sizeof(PointCloudView_FilterOnTile) == 0x000058, "Wrong size on PointCloudView_FilterOnTile");
static_assert(offsetof(PointCloudView_FilterOnTile, QueryGridBounds) == 0x000000, "Member 'PointCloudView_FilterOnTile::QueryGridBounds' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, InNumTilesX) == 0x000038, "Member 'PointCloudView_FilterOnTile::InNumTilesX' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, InNumTilesY) == 0x00003C, "Member 'PointCloudView_FilterOnTile::InNumTilesY' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, InNumTilesZ) == 0x000040, "Member 'PointCloudView_FilterOnTile::InNumTilesZ' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, InTileX) == 0x000044, "Member 'PointCloudView_FilterOnTile::InTileX' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, InTileY) == 0x000048, "Member 'PointCloudView_FilterOnTile::InTileY' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, InTileZ) == 0x00004C, "Member 'PointCloudView_FilterOnTile::InTileZ' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, bInvertSelection) == 0x000050, "Member 'PointCloudView_FilterOnTile::bInvertSelection' has a wrong offset!");
static_assert(offsetof(PointCloudView_FilterOnTile, Mode) == 0x000051, "Member 'PointCloudView_FilterOnTile::Mode' has a wrong offset!");

// Function PointCloud.PointCloudView.MakeChildView
// 0x0008 (0x0008 - 0x0000)
struct PointCloudView_MakeChildView final
{
public:
	class UPointCloudView*                        ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_MakeChildView) == 0x000008, "Wrong alignment on PointCloudView_MakeChildView");
static_assert(sizeof(PointCloudView_MakeChildView) == 0x000008, "Wrong size on PointCloudView_MakeChildView");
static_assert(offsetof(PointCloudView_MakeChildView, ReturnValue) == 0x000000, "Member 'PointCloudView_MakeChildView::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.CountResultsInBox
// 0x0040 (0x0040 - 0x0000)
struct PointCloudView_CountResultsInBox final
{
public:
	struct FBox                                   Box;                                               // 0x0000(0x0038)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0038(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_CountResultsInBox) == 0x000004, "Wrong alignment on PointCloudView_CountResultsInBox");
static_assert(sizeof(PointCloudView_CountResultsInBox) == 0x000040, "Wrong size on PointCloudView_CountResultsInBox");
static_assert(offsetof(PointCloudView_CountResultsInBox, Box) == 0x000000, "Member 'PointCloudView_CountResultsInBox::Box' has a wrong offset!");
static_assert(offsetof(PointCloudView_CountResultsInBox, ReturnValue) == 0x000038, "Member 'PointCloudView_CountResultsInBox::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetCount
// 0x0004 (0x0004 - 0x0000)
struct PointCloudView_GetCount final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetCount) == 0x000004, "Wrong alignment on PointCloudView_GetCount");
static_assert(sizeof(PointCloudView_GetCount) == 0x000004, "Wrong size on PointCloudView_GetCount");
static_assert(offsetof(PointCloudView_GetCount, ReturnValue) == 0x000000, "Member 'PointCloudView_GetCount::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetHash
// 0x0010 (0x0010 - 0x0000)
struct PointCloudView_GetHash final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetHash) == 0x000008, "Wrong alignment on PointCloudView_GetHash");
static_assert(sizeof(PointCloudView_GetHash) == 0x000010, "Wrong size on PointCloudView_GetHash");
static_assert(offsetof(PointCloudView_GetHash, ReturnValue) == 0x000000, "Member 'PointCloudView_GetHash::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetIndexes
// 0x0018 (0x0018 - 0x0000)
struct PointCloudView_GetIndexes final
{
public:
	TArray<int32>                                 OutIds;                                            // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_GetIndexes) == 0x000008, "Wrong alignment on PointCloudView_GetIndexes");
static_assert(sizeof(PointCloudView_GetIndexes) == 0x000018, "Wrong size on PointCloudView_GetIndexes");
static_assert(offsetof(PointCloudView_GetIndexes, OutIds) == 0x000000, "Member 'PointCloudView_GetIndexes::OutIds' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetIndexes, ReturnValue) == 0x000010, "Member 'PointCloudView_GetIndexes::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetMetadata
// 0x0058 (0x0058 - 0x0000)
struct PointCloudView_GetMetadata final
{
public:
	int32                                         PointID;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class FString>            ReturnValue;                                       // 0x0008(0x0050)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetMetadata) == 0x000008, "Wrong alignment on PointCloudView_GetMetadata");
static_assert(sizeof(PointCloudView_GetMetadata) == 0x000058, "Wrong size on PointCloudView_GetMetadata");
static_assert(offsetof(PointCloudView_GetMetadata, PointID) == 0x000000, "Member 'PointCloudView_GetMetadata::PointID' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetMetadata, ReturnValue) == 0x000008, "Member 'PointCloudView_GetMetadata::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetMetadataValues
// 0x0060 (0x0060 - 0x0000)
struct PointCloudView_GetMetadataValues final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<int32, class FString>                    ReturnValue;                                       // 0x0010(0x0050)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetMetadataValues) == 0x000008, "Wrong alignment on PointCloudView_GetMetadataValues");
static_assert(sizeof(PointCloudView_GetMetadataValues) == 0x000060, "Wrong size on PointCloudView_GetMetadataValues");
static_assert(offsetof(PointCloudView_GetMetadataValues, Key) == 0x000000, "Member 'PointCloudView_GetMetadataValues::Key' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetMetadataValues, ReturnValue) == 0x000010, "Member 'PointCloudView_GetMetadataValues::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetMetadataValuesArrayAsFloat
// 0x0020 (0x0020 - 0x0000)
struct PointCloudView_GetMetadataValuesArrayAsFloat final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetMetadataValuesArrayAsFloat) == 0x000008, "Wrong alignment on PointCloudView_GetMetadataValuesArrayAsFloat");
static_assert(sizeof(PointCloudView_GetMetadataValuesArrayAsFloat) == 0x000020, "Wrong size on PointCloudView_GetMetadataValuesArrayAsFloat");
static_assert(offsetof(PointCloudView_GetMetadataValuesArrayAsFloat, Key) == 0x000000, "Member 'PointCloudView_GetMetadataValuesArrayAsFloat::Key' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetMetadataValuesArrayAsFloat, ReturnValue) == 0x000010, "Member 'PointCloudView_GetMetadataValuesArrayAsFloat::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetMetadataValuesArrayAsInt
// 0x0020 (0x0020 - 0x0000)
struct PointCloudView_GetMetadataValuesArrayAsInt final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<int32>                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetMetadataValuesArrayAsInt) == 0x000008, "Wrong alignment on PointCloudView_GetMetadataValuesArrayAsInt");
static_assert(sizeof(PointCloudView_GetMetadataValuesArrayAsInt) == 0x000020, "Wrong size on PointCloudView_GetMetadataValuesArrayAsInt");
static_assert(offsetof(PointCloudView_GetMetadataValuesArrayAsInt, Key) == 0x000000, "Member 'PointCloudView_GetMetadataValuesArrayAsInt::Key' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetMetadataValuesArrayAsInt, ReturnValue) == 0x000010, "Member 'PointCloudView_GetMetadataValuesArrayAsInt::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetPointCloud
// 0x0008 (0x0008 - 0x0000)
struct PointCloudView_GetPointCloud final
{
public:
	class UPointCloud*                            ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetPointCloud) == 0x000008, "Wrong alignment on PointCloudView_GetPointCloud");
static_assert(sizeof(PointCloudView_GetPointCloud) == 0x000008, "Wrong size on PointCloudView_GetPointCloud");
static_assert(offsetof(PointCloudView_GetPointCloud, ReturnValue) == 0x000000, "Member 'PointCloudView_GetPointCloud::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetResultsBoundingBox
// 0x0038 (0x0038 - 0x0000)
struct PointCloudView_GetResultsBoundingBox final
{
public:
	struct FBox                                   ReturnValue;                                       // 0x0000(0x0038)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetResultsBoundingBox) == 0x000001, "Wrong alignment on PointCloudView_GetResultsBoundingBox");
static_assert(sizeof(PointCloudView_GetResultsBoundingBox) == 0x000038, "Wrong size on PointCloudView_GetResultsBoundingBox");
static_assert(offsetof(PointCloudView_GetResultsBoundingBox, ReturnValue) == 0x000000, "Member 'PointCloudView_GetResultsBoundingBox::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetTransforms
// 0x0010 (0x0010 - 0x0000)
struct PointCloudView_GetTransforms final
{
public:
	TArray<struct FTransform>                     ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetTransforms) == 0x000008, "Wrong alignment on PointCloudView_GetTransforms");
static_assert(sizeof(PointCloudView_GetTransforms) == 0x000010, "Wrong size on PointCloudView_GetTransforms");
static_assert(offsetof(PointCloudView_GetTransforms, ReturnValue) == 0x000000, "Member 'PointCloudView_GetTransforms::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetTransformsAndIds
// 0x0028 (0x0028 - 0x0000)
struct PointCloudView_GetTransformsAndIds final
{
public:
	TArray<struct FTransform>                     OutTransforms;                                     // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 OutIds;                                            // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(PointCloudView_GetTransformsAndIds) == 0x000008, "Wrong alignment on PointCloudView_GetTransformsAndIds");
static_assert(sizeof(PointCloudView_GetTransformsAndIds) == 0x000028, "Wrong size on PointCloudView_GetTransformsAndIds");
static_assert(offsetof(PointCloudView_GetTransformsAndIds, OutTransforms) == 0x000000, "Member 'PointCloudView_GetTransformsAndIds::OutTransforms' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetTransformsAndIds, OutIds) == 0x000010, "Member 'PointCloudView_GetTransformsAndIds::OutIds' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetTransformsAndIds, ReturnValue) == 0x000020, "Member 'PointCloudView_GetTransformsAndIds::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetUniqueMetadataValues
// 0x0020 (0x0020 - 0x0000)
struct PointCloudView_GetUniqueMetadataValues final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetUniqueMetadataValues) == 0x000008, "Wrong alignment on PointCloudView_GetUniqueMetadataValues");
static_assert(sizeof(PointCloudView_GetUniqueMetadataValues) == 0x000020, "Wrong size on PointCloudView_GetUniqueMetadataValues");
static_assert(offsetof(PointCloudView_GetUniqueMetadataValues, Key) == 0x000000, "Member 'PointCloudView_GetUniqueMetadataValues::Key' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetUniqueMetadataValues, ReturnValue) == 0x000010, "Member 'PointCloudView_GetUniqueMetadataValues::ReturnValue' has a wrong offset!");

// Function PointCloud.PointCloudView.GetUniqueMetadataValuesAndCounts
// 0x0060 (0x0060 - 0x0000)
struct PointCloudView_GetUniqueMetadataValuesAndCounts final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, int32>                    ReturnValue;                                       // 0x0010(0x0050)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PointCloudView_GetUniqueMetadataValuesAndCounts) == 0x000008, "Wrong alignment on PointCloudView_GetUniqueMetadataValuesAndCounts");
static_assert(sizeof(PointCloudView_GetUniqueMetadataValuesAndCounts) == 0x000060, "Wrong size on PointCloudView_GetUniqueMetadataValuesAndCounts");
static_assert(offsetof(PointCloudView_GetUniqueMetadataValuesAndCounts, Key) == 0x000000, "Member 'PointCloudView_GetUniqueMetadataValuesAndCounts::Key' has a wrong offset!");
static_assert(offsetof(PointCloudView_GetUniqueMetadataValuesAndCounts, ReturnValue) == 0x000010, "Member 'PointCloudView_GetUniqueMetadataValuesAndCounts::ReturnValue' has a wrong offset!");

}

