#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WMActivitySDK

#include "Basic.hpp"


namespace SDK
{

// Enum WMActivitySDK.EWMWebPermissionType
// NumValues: 0x0007
enum class EWMWebPermissionType : uint8
{
	WMWebPermissionTypeNone                  = 0,
	WMWebPermissionTypeMicrophone            = 10,
	WMWebPermissionTypeCamera                = 11,
	WMWebPermissionTypeReadExternalStorage   = 101,
	WMWebPermissionTypeWriteExternalStorage  = 102,
	WMWebPermissionTypePhotoLibrary          = 103,
	EWMWebPermissionType_MAX                 = 104,
};

// Enum WMActivitySDK.EWMAlbumMediaType
// NumValues: 0x0004
enum class EWMAlbumMediaType : uint8
{
	ALL                                      = 0,
	IMAGE                                    = 1,
	VIDEO                                    = 2,
	EWMAlbumMediaType_MAX                    = 3,
};

// Enum WMActivitySDK.EKefuSDKMsgSendStatus
// NumValues: 0x0005
enum class EKefuSDKMsgSendStatus : uint8
{
	ChatSDKMsgSendStatusNotNeed              = 0,
	ChatSDKMsgSendStatusSucceed              = 1,
	ChatSDKMsgSendStatusFail                 = 2,
	ChatSDKMsgSendStatusSending              = 3,
	EKefuSDKMsgSendStatus_MAX                = 4,
};

// Enum WMActivitySDK.EKefuSDKMessageType
// NumValues: 0x000D
enum class EKefuSDKMessageType : uint8
{
	Unknow                                   = 0,
	Text                                     = 1,
	Emoji                                    = 2,
	Image                                    = 3,
	Location                                 = 4,
	Audio                                    = 5,
	Video                                    = 6,
	File                                     = 7,
	Event                                    = 8,
	Pass                                     = 9,
	Custom                                   = 100,
	RichText                                 = 200,
	EKefuSDKMessageType_MAX                  = 201,
};

// Enum WMActivitySDK.EWMAlbumImageEditCompress
// NumValues: 0x0005
enum class EWMAlbumImageEditCompress : uint8
{
	NoCompress                               = 0,
	MinCompress                              = 1,
	MiddleCompress                           = 2,
	MaxCompress                              = 3,
	EWMAlbumImageEditCompress_MAX            = 4,
};

// Enum WMActivitySDK.EWMAlbumImageEditRatio
// NumValues: 0x0005
enum class EWMAlbumImageEditRatio : uint8
{
	Free                                     = 0,
	OneToOne                                 = 1,
	FourToThree                              = 2,
	ThreeToFour                              = 3,
	EWMAlbumImageEditRatio_MAX               = 4,
};

// Enum WMActivitySDK.EWMAudioPlatform
// NumValues: 0x000A
enum class EWMAudioPlatform : uint8
{
	WMAudioPlatformDefault                   = 0,
	WMAudioPlatformGME                       = 1,
	WMAudioPlatformTRTC                      = 2,
	WMAudioPlatformAgora                     = 3,
	WMAudioPlatformAli                       = 4,
	WMAudioPlatformNE                        = 5,
	WMAudioPlatformYoumi                     = 6,
	WMAudioPlatformGVoice                    = 7,
	WMAudioPlatformIFlyMSC                   = 8,
	EWMAudioPlatform_MAX                     = 9,
};

// ScriptStruct WMActivitySDK.ActivityDataRequest
// 0x0088 (0x0088 - 0x0000)
struct FActivityDataRequest final
{
public:
	class FString                                 URL;                                               // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 method;                                            // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 AppID;                                             // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            Params;                                            // 0x0030(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          shouldEncrypt;                                     // 0x0080(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FActivityDataRequest) == 0x000008, "Wrong alignment on FActivityDataRequest");
static_assert(sizeof(FActivityDataRequest) == 0x000088, "Wrong size on FActivityDataRequest");
static_assert(offsetof(FActivityDataRequest, URL) == 0x000000, "Member 'FActivityDataRequest::URL' has a wrong offset!");
static_assert(offsetof(FActivityDataRequest, method) == 0x000010, "Member 'FActivityDataRequest::method' has a wrong offset!");
static_assert(offsetof(FActivityDataRequest, AppID) == 0x000020, "Member 'FActivityDataRequest::AppID' has a wrong offset!");
static_assert(offsetof(FActivityDataRequest, Params) == 0x000030, "Member 'FActivityDataRequest::Params' has a wrong offset!");
static_assert(offsetof(FActivityDataRequest, shouldEncrypt) == 0x000080, "Member 'FActivityDataRequest::shouldEncrypt' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMCOSUploadCallbackInfo
// 0x0048 (0x0048 - 0x0000)
struct FWMCOSUploadCallbackInfo final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Category;                                          // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 URL;                                               // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Code;                                              // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Message;                                           // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMCOSUploadCallbackInfo) == 0x000008, "Wrong alignment on FWMCOSUploadCallbackInfo");
static_assert(sizeof(FWMCOSUploadCallbackInfo) == 0x000048, "Wrong size on FWMCOSUploadCallbackInfo");
static_assert(offsetof(FWMCOSUploadCallbackInfo, Filename) == 0x000000, "Member 'FWMCOSUploadCallbackInfo::Filename' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadCallbackInfo, Category) == 0x000010, "Member 'FWMCOSUploadCallbackInfo::Category' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadCallbackInfo, URL) == 0x000020, "Member 'FWMCOSUploadCallbackInfo::URL' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadCallbackInfo, Code) == 0x000030, "Member 'FWMCOSUploadCallbackInfo::Code' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadCallbackInfo, Message) == 0x000038, "Member 'FWMCOSUploadCallbackInfo::Message' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMCOSDownloadTask
// 0x0078 (0x0078 - 0x0000)
struct FWMCOSDownloadTask final
{
public:
	class FString                                 URL;                                               // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ResultPath;                                        // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Filename;                                          // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ImageEditParams;                                   // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Category;                                          // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 CloudPathPrefix;                                   // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 UniqueIdentifier;                                  // 0x0060(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ResolvingSymlinks;                                 // 0x0070(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMCOSDownloadTask) == 0x000008, "Wrong alignment on FWMCOSDownloadTask");
static_assert(sizeof(FWMCOSDownloadTask) == 0x000078, "Wrong size on FWMCOSDownloadTask");
static_assert(offsetof(FWMCOSDownloadTask, URL) == 0x000000, "Member 'FWMCOSDownloadTask::URL' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, ResultPath) == 0x000010, "Member 'FWMCOSDownloadTask::ResultPath' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, Filename) == 0x000020, "Member 'FWMCOSDownloadTask::Filename' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, ImageEditParams) == 0x000030, "Member 'FWMCOSDownloadTask::ImageEditParams' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, Category) == 0x000040, "Member 'FWMCOSDownloadTask::Category' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, CloudPathPrefix) == 0x000050, "Member 'FWMCOSDownloadTask::CloudPathPrefix' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, UniqueIdentifier) == 0x000060, "Member 'FWMCOSDownloadTask::UniqueIdentifier' has a wrong offset!");
static_assert(offsetof(FWMCOSDownloadTask, ResolvingSymlinks) == 0x000070, "Member 'FWMCOSDownloadTask::ResolvingSymlinks' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMActivityWebViewConfiguration
// 0x0030 (0x0030 - 0x0000)
struct FWMActivityWebViewConfiguration final
{
public:
	float                                         X;                                                 // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Y;                                                 // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Width;                                             // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Height;                                            // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          scrollEnabled;                                     // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         barStyle;                                          // 0x0011(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isSurvey;                                          // 0x0012(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 bgColor;                                           // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          canTouchOutside;                                   // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         orientation;                                       // 0x0029(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMActivityWebViewConfiguration) == 0x000008, "Wrong alignment on FWMActivityWebViewConfiguration");
static_assert(sizeof(FWMActivityWebViewConfiguration) == 0x000030, "Wrong size on FWMActivityWebViewConfiguration");
static_assert(offsetof(FWMActivityWebViewConfiguration, X) == 0x000000, "Member 'FWMActivityWebViewConfiguration::X' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, Y) == 0x000004, "Member 'FWMActivityWebViewConfiguration::Y' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, Width) == 0x000008, "Member 'FWMActivityWebViewConfiguration::Width' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, Height) == 0x00000C, "Member 'FWMActivityWebViewConfiguration::Height' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, scrollEnabled) == 0x000010, "Member 'FWMActivityWebViewConfiguration::scrollEnabled' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, barStyle) == 0x000011, "Member 'FWMActivityWebViewConfiguration::barStyle' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, isSurvey) == 0x000012, "Member 'FWMActivityWebViewConfiguration::isSurvey' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, bgColor) == 0x000018, "Member 'FWMActivityWebViewConfiguration::bgColor' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, canTouchOutside) == 0x000028, "Member 'FWMActivityWebViewConfiguration::canTouchOutside' has a wrong offset!");
static_assert(offsetof(FWMActivityWebViewConfiguration, orientation) == 0x000029, "Member 'FWMActivityWebViewConfiguration::orientation' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMCompressImageConfig
// 0x0030 (0x0030 - 0x0000)
struct FWMCompressImageConfig final
{
public:
	class FString                                 ImagePath;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ThumbnailPath;                                     // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailWidth;                                    // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailHeight;                                   // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailCompression;                              // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMCompressImageConfig) == 0x000008, "Wrong alignment on FWMCompressImageConfig");
static_assert(sizeof(FWMCompressImageConfig) == 0x000030, "Wrong size on FWMCompressImageConfig");
static_assert(offsetof(FWMCompressImageConfig, ImagePath) == 0x000000, "Member 'FWMCompressImageConfig::ImagePath' has a wrong offset!");
static_assert(offsetof(FWMCompressImageConfig, ThumbnailPath) == 0x000010, "Member 'FWMCompressImageConfig::ThumbnailPath' has a wrong offset!");
static_assert(offsetof(FWMCompressImageConfig, ThumbnailWidth) == 0x000020, "Member 'FWMCompressImageConfig::ThumbnailWidth' has a wrong offset!");
static_assert(offsetof(FWMCompressImageConfig, ThumbnailHeight) == 0x000024, "Member 'FWMCompressImageConfig::ThumbnailHeight' has a wrong offset!");
static_assert(offsetof(FWMCompressImageConfig, ThumbnailCompression) == 0x000028, "Member 'FWMCompressImageConfig::ThumbnailCompression' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMAlbumMediaInfo
// 0x0040 (0x0040 - 0x0000)
struct FWMAlbumMediaInfo final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         FileSize;                                          // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Width;                                             // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Height;                                            // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EWMAlbumMediaType                             MediaType;                                         // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CoverPath;                                         // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         duration;                                          // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMAlbumMediaInfo) == 0x000008, "Wrong alignment on FWMAlbumMediaInfo");
static_assert(sizeof(FWMAlbumMediaInfo) == 0x000040, "Wrong size on FWMAlbumMediaInfo");
static_assert(offsetof(FWMAlbumMediaInfo, FilePath) == 0x000000, "Member 'FWMAlbumMediaInfo::FilePath' has a wrong offset!");
static_assert(offsetof(FWMAlbumMediaInfo, FileSize) == 0x000010, "Member 'FWMAlbumMediaInfo::FileSize' has a wrong offset!");
static_assert(offsetof(FWMAlbumMediaInfo, Width) == 0x000018, "Member 'FWMAlbumMediaInfo::Width' has a wrong offset!");
static_assert(offsetof(FWMAlbumMediaInfo, Height) == 0x00001C, "Member 'FWMAlbumMediaInfo::Height' has a wrong offset!");
static_assert(offsetof(FWMAlbumMediaInfo, MediaType) == 0x000020, "Member 'FWMAlbumMediaInfo::MediaType' has a wrong offset!");
static_assert(offsetof(FWMAlbumMediaInfo, CoverPath) == 0x000028, "Member 'FWMAlbumMediaInfo::CoverPath' has a wrong offset!");
static_assert(offsetof(FWMAlbumMediaInfo, duration) == 0x000038, "Member 'FWMAlbumMediaInfo::duration' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMAudioPlayerInfoBean
// 0x0030 (0x0030 - 0x0000)
struct FWMAudioPlayerInfoBean final
{
public:
	class FString                                 AudioUrl;                                          // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 FileId;                                            // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Rate;                                              // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         StartPosition;                                     // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         duration;                                          // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlayState;                                         // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMAudioPlayerInfoBean) == 0x000008, "Wrong alignment on FWMAudioPlayerInfoBean");
static_assert(sizeof(FWMAudioPlayerInfoBean) == 0x000030, "Wrong size on FWMAudioPlayerInfoBean");
static_assert(offsetof(FWMAudioPlayerInfoBean, AudioUrl) == 0x000000, "Member 'FWMAudioPlayerInfoBean::AudioUrl' has a wrong offset!");
static_assert(offsetof(FWMAudioPlayerInfoBean, FileId) == 0x000010, "Member 'FWMAudioPlayerInfoBean::FileId' has a wrong offset!");
static_assert(offsetof(FWMAudioPlayerInfoBean, Rate) == 0x000020, "Member 'FWMAudioPlayerInfoBean::Rate' has a wrong offset!");
static_assert(offsetof(FWMAudioPlayerInfoBean, StartPosition) == 0x000024, "Member 'FWMAudioPlayerInfoBean::StartPosition' has a wrong offset!");
static_assert(offsetof(FWMAudioPlayerInfoBean, duration) == 0x000028, "Member 'FWMAudioPlayerInfoBean::duration' has a wrong offset!");
static_assert(offsetof(FWMAudioPlayerInfoBean, PlayState) == 0x00002C, "Member 'FWMAudioPlayerInfoBean::PlayState' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMActivityRoleInfo
// 0x0070 (0x0070 - 0x0000)
struct FWMActivityRoleInfo final
{
public:
	class FString                                 UserId;                                            // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoleId;                                            // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoleName;                                          // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ServerId;                                          // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ServerName;                                        // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 LastLogin;                                         // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         Level;                                             // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Gender;                                            // 0x0068(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Occupation;                                        // 0x006C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMActivityRoleInfo) == 0x000008, "Wrong alignment on FWMActivityRoleInfo");
static_assert(sizeof(FWMActivityRoleInfo) == 0x000070, "Wrong size on FWMActivityRoleInfo");
static_assert(offsetof(FWMActivityRoleInfo, UserId) == 0x000000, "Member 'FWMActivityRoleInfo::UserId' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, RoleId) == 0x000010, "Member 'FWMActivityRoleInfo::RoleId' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, RoleName) == 0x000020, "Member 'FWMActivityRoleInfo::RoleName' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, ServerId) == 0x000030, "Member 'FWMActivityRoleInfo::ServerId' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, ServerName) == 0x000040, "Member 'FWMActivityRoleInfo::ServerName' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, LastLogin) == 0x000050, "Member 'FWMActivityRoleInfo::LastLogin' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, Level) == 0x000060, "Member 'FWMActivityRoleInfo::Level' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, Gender) == 0x000068, "Member 'FWMActivityRoleInfo::Gender' has a wrong offset!");
static_assert(offsetof(FWMActivityRoleInfo, Occupation) == 0x00006C, "Member 'FWMActivityRoleInfo::Occupation' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMCOSUploadTask
// 0x0078 (0x0078 - 0x0000)
struct FWMCOSUploadTask final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 Data;                                              // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 Filename;                                          // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Category;                                          // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 CloudPathPrefix;                                   // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Sign;                                              // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ContentMD5;                                        // 0x0060(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ContentLength;                                     // 0x0070(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMCOSUploadTask) == 0x000008, "Wrong alignment on FWMCOSUploadTask");
static_assert(sizeof(FWMCOSUploadTask) == 0x000078, "Wrong size on FWMCOSUploadTask");
static_assert(offsetof(FWMCOSUploadTask, Path) == 0x000000, "Member 'FWMCOSUploadTask::Path' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, Data) == 0x000010, "Member 'FWMCOSUploadTask::Data' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, Filename) == 0x000020, "Member 'FWMCOSUploadTask::Filename' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, Category) == 0x000030, "Member 'FWMCOSUploadTask::Category' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, CloudPathPrefix) == 0x000040, "Member 'FWMCOSUploadTask::CloudPathPrefix' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, Sign) == 0x000050, "Member 'FWMCOSUploadTask::Sign' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, ContentMD5) == 0x000060, "Member 'FWMCOSUploadTask::ContentMD5' has a wrong offset!");
static_assert(offsetof(FWMCOSUploadTask, ContentLength) == 0x000070, "Member 'FWMCOSUploadTask::ContentLength' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMKefuServiceInfo
// 0x0070 (0x0070 - 0x0000)
struct FWMKefuServiceInfo final
{
public:
	class FString                                 ServiceName;                                       // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ServiceLevel;                                      // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ServiceAvatar;                                     // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ServiceMood;                                       // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsOnline;                                         // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ServiceGsImId;                                     // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Ext;                                               // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ExperienceStartTime;                               // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ExperienceEndTime;                                 // 0x0068(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMKefuServiceInfo) == 0x000008, "Wrong alignment on FWMKefuServiceInfo");
static_assert(sizeof(FWMKefuServiceInfo) == 0x000070, "Wrong size on FWMKefuServiceInfo");
static_assert(offsetof(FWMKefuServiceInfo, ServiceName) == 0x000000, "Member 'FWMKefuServiceInfo::ServiceName' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, ServiceLevel) == 0x000010, "Member 'FWMKefuServiceInfo::ServiceLevel' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, ServiceAvatar) == 0x000018, "Member 'FWMKefuServiceInfo::ServiceAvatar' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, ServiceMood) == 0x000028, "Member 'FWMKefuServiceInfo::ServiceMood' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, bIsOnline) == 0x000038, "Member 'FWMKefuServiceInfo::bIsOnline' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, ServiceGsImId) == 0x000040, "Member 'FWMKefuServiceInfo::ServiceGsImId' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, Ext) == 0x000050, "Member 'FWMKefuServiceInfo::Ext' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, ExperienceStartTime) == 0x000060, "Member 'FWMKefuServiceInfo::ExperienceStartTime' has a wrong offset!");
static_assert(offsetof(FWMKefuServiceInfo, ExperienceEndTime) == 0x000068, "Member 'FWMKefuServiceInfo::ExperienceEndTime' has a wrong offset!");

// ScriptStruct WMActivitySDK.KefuSDKMessageData
// 0x0100 (0x0100 - 0x0000)
struct FKefuSDKMessageData final
{
public:
	class FString                                 ClientMsgId;                                       // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         MsgId;                                             // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 MsgSeq;                                            // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         MsgTime;                                           // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsFromMe;                                         // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 From;                                              // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAtAll;                                            // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         AtUserList;                                        // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          bAtMe;                                             // 0x0060(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EKefuSDKMessageType                           MsgType;                                           // 0x0061(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_62[0x6];                                       // 0x0062(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UKefuSDKTextMessage*                    TxtMsg;                                            // 0x0068(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKEmojiMessage*                   EmojiMsg;                                          // 0x0070(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKImageMessage*                   ImageMsg;                                          // 0x0078(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKLocationMessage*                LocationMsg;                                       // 0x0080(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKAudioMessage*                   AudioMsg;                                          // 0x0088(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKVideoMessage*                   VideoMsg;                                          // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKFileMessage*                    FileMsg;                                           // 0x0098(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKPassMessage*                    PassMsg;                                           // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UKefuSDKCustomMessage*                  CustomMsg;                                         // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EventMsg;                                          // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Ext;                                               // 0x00C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EKefuSDKMsgSendStatus                         SendStatus;                                        // 0x00D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsRead;                                           // 0x00D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D2[0x6];                                       // 0x00D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LocalExt;                                          // 0x00D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsAuditFailed;                                    // 0x00E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LogInfo;                                           // 0x00F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FKefuSDKMessageData) == 0x000008, "Wrong alignment on FKefuSDKMessageData");
static_assert(sizeof(FKefuSDKMessageData) == 0x000100, "Wrong size on FKefuSDKMessageData");
static_assert(offsetof(FKefuSDKMessageData, ClientMsgId) == 0x000000, "Member 'FKefuSDKMessageData::ClientMsgId' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, MsgId) == 0x000010, "Member 'FKefuSDKMessageData::MsgId' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, MsgSeq) == 0x000018, "Member 'FKefuSDKMessageData::MsgSeq' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, MsgTime) == 0x000028, "Member 'FKefuSDKMessageData::MsgTime' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, bIsFromMe) == 0x000030, "Member 'FKefuSDKMessageData::bIsFromMe' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, From) == 0x000038, "Member 'FKefuSDKMessageData::From' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, bAtAll) == 0x000048, "Member 'FKefuSDKMessageData::bAtAll' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, AtUserList) == 0x000050, "Member 'FKefuSDKMessageData::AtUserList' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, bAtMe) == 0x000060, "Member 'FKefuSDKMessageData::bAtMe' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, MsgType) == 0x000061, "Member 'FKefuSDKMessageData::MsgType' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, TxtMsg) == 0x000068, "Member 'FKefuSDKMessageData::TxtMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, EmojiMsg) == 0x000070, "Member 'FKefuSDKMessageData::EmojiMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, ImageMsg) == 0x000078, "Member 'FKefuSDKMessageData::ImageMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, LocationMsg) == 0x000080, "Member 'FKefuSDKMessageData::LocationMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, AudioMsg) == 0x000088, "Member 'FKefuSDKMessageData::AudioMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, VideoMsg) == 0x000090, "Member 'FKefuSDKMessageData::VideoMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, FileMsg) == 0x000098, "Member 'FKefuSDKMessageData::FileMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, PassMsg) == 0x0000A0, "Member 'FKefuSDKMessageData::PassMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, CustomMsg) == 0x0000A8, "Member 'FKefuSDKMessageData::CustomMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, EventMsg) == 0x0000B0, "Member 'FKefuSDKMessageData::EventMsg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, Ext) == 0x0000C0, "Member 'FKefuSDKMessageData::Ext' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, SendStatus) == 0x0000D0, "Member 'FKefuSDKMessageData::SendStatus' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, bIsRead) == 0x0000D1, "Member 'FKefuSDKMessageData::bIsRead' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, LocalExt) == 0x0000D8, "Member 'FKefuSDKMessageData::LocalExt' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, bIsAuditFailed) == 0x0000E8, "Member 'FKefuSDKMessageData::bIsAuditFailed' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessageData, LogInfo) == 0x0000F0, "Member 'FKefuSDKMessageData::LogInfo' has a wrong offset!");

// ScriptStruct WMActivitySDK.KefuSDKMessage
// 0x0118 (0x0118 - 0x0000)
struct FKefuSDKMessage final
{
public:
	struct FKefuSDKMessageData                    Msg;                                               // 0x0000(0x0100)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          bIsCancel;                                         // 0x0100(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 To;                                                // 0x0108(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FKefuSDKMessage) == 0x000008, "Wrong alignment on FKefuSDKMessage");
static_assert(sizeof(FKefuSDKMessage) == 0x000118, "Wrong size on FKefuSDKMessage");
static_assert(offsetof(FKefuSDKMessage, Msg) == 0x000000, "Member 'FKefuSDKMessage::Msg' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessage, bIsCancel) == 0x000100, "Member 'FKefuSDKMessage::bIsCancel' has a wrong offset!");
static_assert(offsetof(FKefuSDKMessage, To) == 0x000108, "Member 'FKefuSDKMessage::To' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMAlbumInfo
// 0x001C (0x001C - 0x0000)
struct FWMAlbumInfo final
{
public:
	EWMAlbumMediaType                             OpenType;                                          // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxCount;                                          // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNeedCut;                                          // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNeedCompress;                                     // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ImageLimitSize;                                    // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         VideoLimitSize;                                    // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         VideoLimitDuration;                                // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShowCamera;                                       // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMAlbumInfo) == 0x000004, "Wrong alignment on FWMAlbumInfo");
static_assert(sizeof(FWMAlbumInfo) == 0x00001C, "Wrong size on FWMAlbumInfo");
static_assert(offsetof(FWMAlbumInfo, OpenType) == 0x000000, "Member 'FWMAlbumInfo::OpenType' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, MaxCount) == 0x000004, "Member 'FWMAlbumInfo::MaxCount' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, bNeedCut) == 0x000008, "Member 'FWMAlbumInfo::bNeedCut' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, bNeedCompress) == 0x000009, "Member 'FWMAlbumInfo::bNeedCompress' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, ImageLimitSize) == 0x00000C, "Member 'FWMAlbumInfo::ImageLimitSize' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, VideoLimitSize) == 0x000010, "Member 'FWMAlbumInfo::VideoLimitSize' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, VideoLimitDuration) == 0x000014, "Member 'FWMAlbumInfo::VideoLimitDuration' has a wrong offset!");
static_assert(offsetof(FWMAlbumInfo, bShowCamera) == 0x000018, "Member 'FWMAlbumInfo::bShowCamera' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMActivityGameRoleInfo
// 0x0140 (0x0140 - 0x0000)
struct FWMActivityGameRoleInfo final
{
public:
	class FString                                 AppID;                                             // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 uid;                                               // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Token;                                             // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 serviceId;                                         // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ServiceName;                                       // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoleId;                                            // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoleName;                                          // 0x0060(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoleLevel;                                         // 0x0070(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 roleVip;                                           // 0x0080(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Gender;                                            // 0x0090(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Occupation;                                        // 0x00A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 sect;                                              // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 userCharge;                                        // 0x00C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 offlineDuration;                                   // 0x00D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Avatar;                                            // 0x00E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            Ext;                                               // 0x00F0(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMActivityGameRoleInfo) == 0x000008, "Wrong alignment on FWMActivityGameRoleInfo");
static_assert(sizeof(FWMActivityGameRoleInfo) == 0x000140, "Wrong size on FWMActivityGameRoleInfo");
static_assert(offsetof(FWMActivityGameRoleInfo, AppID) == 0x000000, "Member 'FWMActivityGameRoleInfo::AppID' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, uid) == 0x000010, "Member 'FWMActivityGameRoleInfo::uid' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, Token) == 0x000020, "Member 'FWMActivityGameRoleInfo::Token' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, serviceId) == 0x000030, "Member 'FWMActivityGameRoleInfo::serviceId' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, ServiceName) == 0x000040, "Member 'FWMActivityGameRoleInfo::ServiceName' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, RoleId) == 0x000050, "Member 'FWMActivityGameRoleInfo::RoleId' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, RoleName) == 0x000060, "Member 'FWMActivityGameRoleInfo::RoleName' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, RoleLevel) == 0x000070, "Member 'FWMActivityGameRoleInfo::RoleLevel' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, roleVip) == 0x000080, "Member 'FWMActivityGameRoleInfo::roleVip' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, Gender) == 0x000090, "Member 'FWMActivityGameRoleInfo::Gender' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, Occupation) == 0x0000A0, "Member 'FWMActivityGameRoleInfo::Occupation' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, sect) == 0x0000B0, "Member 'FWMActivityGameRoleInfo::sect' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, userCharge) == 0x0000C0, "Member 'FWMActivityGameRoleInfo::userCharge' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, offlineDuration) == 0x0000D0, "Member 'FWMActivityGameRoleInfo::offlineDuration' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, Avatar) == 0x0000E0, "Member 'FWMActivityGameRoleInfo::Avatar' has a wrong offset!");
static_assert(offsetof(FWMActivityGameRoleInfo, Ext) == 0x0000F0, "Member 'FWMActivityGameRoleInfo::Ext' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMAlbumSingleImageConfig
// 0x0030 (0x0030 - 0x0000)
struct FWMAlbumSingleImageConfig final
{
public:
	bool                                          bForceEdit;                                        // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EWMAlbumImageEditRatio>                EditRatio;                                         // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         OutputWidth;                                       // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutputHeight;                                      // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EWMAlbumImageEditCompress                     Compresss;                                         // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ScreenScale;                                       // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShowOriginCutRate;                                 // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMAlbumSingleImageConfig) == 0x000008, "Wrong alignment on FWMAlbumSingleImageConfig");
static_assert(sizeof(FWMAlbumSingleImageConfig) == 0x000030, "Wrong size on FWMAlbumSingleImageConfig");
static_assert(offsetof(FWMAlbumSingleImageConfig, bForceEdit) == 0x000000, "Member 'FWMAlbumSingleImageConfig::bForceEdit' has a wrong offset!");
static_assert(offsetof(FWMAlbumSingleImageConfig, EditRatio) == 0x000008, "Member 'FWMAlbumSingleImageConfig::EditRatio' has a wrong offset!");
static_assert(offsetof(FWMAlbumSingleImageConfig, OutputWidth) == 0x000018, "Member 'FWMAlbumSingleImageConfig::OutputWidth' has a wrong offset!");
static_assert(offsetof(FWMAlbumSingleImageConfig, OutputHeight) == 0x00001C, "Member 'FWMAlbumSingleImageConfig::OutputHeight' has a wrong offset!");
static_assert(offsetof(FWMAlbumSingleImageConfig, Compresss) == 0x000020, "Member 'FWMAlbumSingleImageConfig::Compresss' has a wrong offset!");
static_assert(offsetof(FWMAlbumSingleImageConfig, ScreenScale) == 0x000024, "Member 'FWMAlbumSingleImageConfig::ScreenScale' has a wrong offset!");
static_assert(offsetof(FWMAlbumSingleImageConfig, ShowOriginCutRate) == 0x000028, "Member 'FWMAlbumSingleImageConfig::ShowOriginCutRate' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMImageEditConfig
// 0x0028 (0x0028 - 0x0000)
struct FWMImageEditConfig final
{
public:
	class FString                                 ImageAbsolutePath;                                 // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 ImageData;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          bSaveAlbum;                                        // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMImageEditConfig) == 0x000008, "Wrong alignment on FWMImageEditConfig");
static_assert(sizeof(FWMImageEditConfig) == 0x000028, "Wrong size on FWMImageEditConfig");
static_assert(offsetof(FWMImageEditConfig, ImageAbsolutePath) == 0x000000, "Member 'FWMImageEditConfig::ImageAbsolutePath' has a wrong offset!");
static_assert(offsetof(FWMImageEditConfig, ImageData) == 0x000010, "Member 'FWMImageEditConfig::ImageData' has a wrong offset!");
static_assert(offsetof(FWMImageEditConfig, bSaveAlbum) == 0x000020, "Member 'FWMImageEditConfig::bSaveAlbum' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMAudioInfo
// 0x0040 (0x0040 - 0x0000)
struct FWMAudioInfo final
{
public:
	class FString                                 AudioUrl;                                          // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Rate;                                              // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         StartPosition;                                     // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 FileId;                                            // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 FileSign;                                          // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PlatformType;                                      // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMAudioInfo) == 0x000008, "Wrong alignment on FWMAudioInfo");
static_assert(sizeof(FWMAudioInfo) == 0x000040, "Wrong size on FWMAudioInfo");
static_assert(offsetof(FWMAudioInfo, AudioUrl) == 0x000000, "Member 'FWMAudioInfo::AudioUrl' has a wrong offset!");
static_assert(offsetof(FWMAudioInfo, Rate) == 0x000010, "Member 'FWMAudioInfo::Rate' has a wrong offset!");
static_assert(offsetof(FWMAudioInfo, StartPosition) == 0x000014, "Member 'FWMAudioInfo::StartPosition' has a wrong offset!");
static_assert(offsetof(FWMAudioInfo, FileId) == 0x000018, "Member 'FWMAudioInfo::FileId' has a wrong offset!");
static_assert(offsetof(FWMAudioInfo, FileSign) == 0x000028, "Member 'FWMAudioInfo::FileSign' has a wrong offset!");
static_assert(offsetof(FWMAudioInfo, PlatformType) == 0x000038, "Member 'FWMAudioInfo::PlatformType' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMShareToForumInfo
// 0x0028 (0x0028 - 0x0000)
struct FWMShareToForumInfo final
{
public:
	class FString                                 ImageAbsolutePath;                                 // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 ImageData;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         ShareType;                                         // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         VideoLimitSize;                                    // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMShareToForumInfo) == 0x000008, "Wrong alignment on FWMShareToForumInfo");
static_assert(sizeof(FWMShareToForumInfo) == 0x000028, "Wrong size on FWMShareToForumInfo");
static_assert(offsetof(FWMShareToForumInfo, ImageAbsolutePath) == 0x000000, "Member 'FWMShareToForumInfo::ImageAbsolutePath' has a wrong offset!");
static_assert(offsetof(FWMShareToForumInfo, ImageData) == 0x000010, "Member 'FWMShareToForumInfo::ImageData' has a wrong offset!");
static_assert(offsetof(FWMShareToForumInfo, ShareType) == 0x000020, "Member 'FWMShareToForumInfo::ShareType' has a wrong offset!");
static_assert(offsetof(FWMShareToForumInfo, VideoLimitSize) == 0x000024, "Member 'FWMShareToForumInfo::VideoLimitSize' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMScreenRecordingResult
// 0x0060 (0x0060 - 0x0000)
struct FWMScreenRecordingResult final
{
public:
	int64                                         StartTime;                                         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 VideoFile;                                         // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ThumbnailFile;                                     // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ThumbnailSmallFile;                                // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         FileSize;                                          // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         VideoRate;                                         // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailWidth;                                    // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailHeight;                                   // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ThumbnailFileSize;                                 // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ThumbnailSmallFileSize;                            // 0x0058(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FWMScreenRecordingResult) == 0x000008, "Wrong alignment on FWMScreenRecordingResult");
static_assert(sizeof(FWMScreenRecordingResult) == 0x000060, "Wrong size on FWMScreenRecordingResult");
static_assert(offsetof(FWMScreenRecordingResult, StartTime) == 0x000000, "Member 'FWMScreenRecordingResult::StartTime' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, VideoFile) == 0x000008, "Member 'FWMScreenRecordingResult::VideoFile' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, ThumbnailFile) == 0x000018, "Member 'FWMScreenRecordingResult::ThumbnailFile' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, ThumbnailSmallFile) == 0x000028, "Member 'FWMScreenRecordingResult::ThumbnailSmallFile' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, FileSize) == 0x000038, "Member 'FWMScreenRecordingResult::FileSize' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, VideoRate) == 0x000040, "Member 'FWMScreenRecordingResult::VideoRate' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, ThumbnailWidth) == 0x000048, "Member 'FWMScreenRecordingResult::ThumbnailWidth' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, ThumbnailHeight) == 0x00004C, "Member 'FWMScreenRecordingResult::ThumbnailHeight' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, ThumbnailFileSize) == 0x000050, "Member 'FWMScreenRecordingResult::ThumbnailFileSize' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingResult, ThumbnailSmallFileSize) == 0x000058, "Member 'FWMScreenRecordingResult::ThumbnailSmallFileSize' has a wrong offset!");

// ScriptStruct WMActivitySDK.WMScreenRecordingConfig
// 0x0030 (0x0030 - 0x0000)
struct FWMScreenRecordingConfig final
{
public:
	class FString                                 RecordFileDir;                                     // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RecordFileName;                                    // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailCompression;                              // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailHeight;                                   // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ThumbnailWidth;                                    // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAudioEnable;                                      // 0x002C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FWMScreenRecordingConfig) == 0x000008, "Wrong alignment on FWMScreenRecordingConfig");
static_assert(sizeof(FWMScreenRecordingConfig) == 0x000030, "Wrong size on FWMScreenRecordingConfig");
static_assert(offsetof(FWMScreenRecordingConfig, RecordFileDir) == 0x000000, "Member 'FWMScreenRecordingConfig::RecordFileDir' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingConfig, RecordFileName) == 0x000010, "Member 'FWMScreenRecordingConfig::RecordFileName' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingConfig, ThumbnailCompression) == 0x000020, "Member 'FWMScreenRecordingConfig::ThumbnailCompression' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingConfig, ThumbnailHeight) == 0x000024, "Member 'FWMScreenRecordingConfig::ThumbnailHeight' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingConfig, ThumbnailWidth) == 0x000028, "Member 'FWMScreenRecordingConfig::ThumbnailWidth' has a wrong offset!");
static_assert(offsetof(FWMScreenRecordingConfig, bAudioEnable) == 0x00002C, "Member 'FWMScreenRecordingConfig::bAudioEnable' has a wrong offset!");

}

