// Synthetic, development-only evidence. Never used as live capture data.
import {
  MAIN_DPS_DETAIL_CONTRACT_VERSION,
  type MainDpsDetailSnapshot,
} from "@/lib/tauri/main-dps-detail-contract";
import { DEFAULT_DETAIL_COLUMNS } from "@/features/main-dps/main-dps-detail-model";
import type {
  HitSnapshot,
  AttributeSnapshot,
} from "@/lib/tauri/hit-snapshot-contract";
const attributes: AttributeSnapshot = {
  id: "9007199254740993",
  generation: "1",
  sampledUnixUs: "1790408242725270",
  finishedUnixUs: "1790408242725300",
  actorIndex: 10,
  actorSerial: 7,
  actorName: "示例角色",
  stage: "hit_callback",
  status: "partial",
  values: {
    hp: { value: 0, status: "ok", source: "HTAttributeComponent.GetHPCurrent" },
    maxHp: {
      value: 25000,
      status: "ok",
      source: "HTAttributeComponent.GetHPMax",
    },
    attack: {
      value: 12345.5,
      status: "ok",
      source: "HTAttributeComponent.GetAtk",
    },
    defense: {
      value: 850,
      status: "ok",
      source: "HTAttributeComponent.GetDef",
    },
    crit: {
      value: null,
      status: "call_failed",
      source: "HTAttributeComponent.GetCrit",
    },
    isBalancedingState: {
      value: false,
      status: "ok",
      source: "HTAttributeComponent.IsBalancedingState",
    },
  },
};
export const hitSnapshotFixture: HitSnapshot = {
  key: "preview-capture:1",
  critical: true,
  criticalSource: "native_prediction",
  retention: "available",
  roleEffects: { positive: 5, negative: 0, other: 55, complete: true },
  enemyEffects: { positive: 0, negative: 1, other: 0, complete: false },
  data: {
    attackerAttributes: attributes,
    victimAttributes: {
      ...attributes,
      id: "2",
      actorIndex: 20,
      actorName: "示例敌人",
      values: {
        hp: {
          value: 120000,
          status: "ok",
          source: "HTAttributeComponent.GetHPCurrent",
        },
      },
    },
    attackerEffects: {
      id: "3",
      actorIndex: 10,
      actorSerial: 7,
      observedUs: "1790408242725270",
      complete: true,
      status: "ok",
      effects: Array.from({ length: 60 }, (_, i) => ({
        instanceKey: `preview:effect:${i}`,
        key: `GE_Preview_${i}`,
        name: `示例状态 ${i + 1}`,
        description:
          "离线示例：这里显示命中当时记录的状态说明，不表示本击施加了该效果。",
        source: "Preview only",
        kind: i < 5 ? 2 : 1,
        stacks: (i % 3) + 1,
        duration: i % 2 ? -1 : 12.5,
        startWorldTime: 15,
        level: 1,
        inhibited: i === 5,
      })),
    },
    victimEffects: {
      id: "4",
      actorIndex: 20,
      actorSerial: 8,
      observedUs: "1790408242725270",
      complete: false,
      status: "partial",
      effects: [
        {
          instanceKey: "preview:enemy:1",
          key: "GE_Preview_Debuff",
          name: "示例减益",
          description: "未完整采得的状态列表",
          source: "Preview only",
          kind: 3,
          stacks: 1,
          duration: 8,
          startWorldTime: 10,
          level: 1,
          inhibited: false,
        },
      ],
    },
  },
};
export const hitDetailsFixture: MainDpsDetailSnapshot = {
  contractVersion: MAIN_DPS_DETAIL_CONTRACT_VERSION,
  generation: "1",
  kind: "character",
  abyssHalf: null,
  characterId: 1042,
  characterName: "黑羽（示例）",
  characterColor: null,
  filter: "all",
  qteType: null,
  skillFilter: null,
  columns: DEFAULT_DETAIL_COLUMNS,
  actions: { canStartCapture: false, canImportReplay: false },
  metrics: {
    totalOutput: 7568,
    dps: 1261,
    outputCount: 3,
    incomingCount: 0,
    totalDamageTaken: 0,
    durationSeconds: 6,
  },
  direction: {
    confirmedOutput: 7568,
    confirmedHits: 3,
    candidateOutput: 0,
    candidateHits: 0,
    incomingOutput: 0,
    incomingHits: 0,
    candidateSharePercent: 0,
  },
  hitTypes: [
    { id: "all", hits: 3, damage: 7568 },
    { id: "outgoing", hits: 3, damage: 7568 },
    { id: "incoming", hits: 0, damage: 0 },
  ],
  attribution: {
    totalDamage: 7568,
    characterDamage: 7568,
    characterFilter: "characterAttributed",
    reactionDamage: 0,
    sharedDamage: 0,
    unattributedDamage: 0,
    separateReactionDamage: false,
  },
  qteSummaries: [],
  qteSummaryTotalCount: 0,
  qteSummariesTruncated: false,
  skills: [],
  skillTotalCount: 0,
  skillsTruncated: false,
  textTruncated: false,
  totalHits: 3,
  totalDamage: 7568,
  maxRowDamage: 4670,
  offset: 0,
  rows: [948, 1950, 4670].map((damage, i) => ({
    id: `preview-hit-${i + 1}`,
    timestamp: 1790408242 + i,
    characterId: 1042,
    characterName: "黑羽（示例）",
    direction: "outgoing",
    damage,
    primaryDamage: damage,
    followUpDamage: 0,
    overkillDamage: null,
    maxHpReduction: null,
    skillId: "preview-skill",
    skill: "示例攻击",
    damageType: "普通攻击",
    typeLabel: "示例攻击",
    reactionTextKey: null,
    damageDigitKey: null,
    followUpDamageDigitKey: null,
    target: "示例敌人",
    targetMonsterId: null,
    targetHpAfter: 120000 - i * damage,
    targetMaxHp: 150000,
    targetHpPercent: 80,
    critical: i === 0 ? true : i === 1 ? false : null,
    snapshotKey: String(i + 1),
    snapshotRetention: "available",
    roleEffects: hitSnapshotFixture.roleEffects,
    enemyEffects: hitSnapshotFixture.enemyEffects,
  })),
};
