from pathlib import Path
import json


artifact = Path(__file__).resolve().parent
results = json.loads((artifact / "validation-results.json").read_text(encoding="utf-8-sig"))
baseline = (artifact / "baseline-behavior.json").read_text(encoding="utf-8-sig").strip()
modified = (artifact / "modified-behavior.json").read_text(encoding="utf-8-sig").strip()

lines = [
    "# History parity verification",
    "",
    "## Inputs",
    "",
    f"- Scoped files: `{artifact / 'scoped-files.txt'}` (13 files)",
    f"- Baseline snapshot: `{artifact / 'original'}`",
    f"- Modified snapshot: `{artifact / 'modified-snapshot'}`",
    "",
    "## Baseline behavior",
    "",
    f"Command: `python {artifact / 'behavior_probe.py'} {artifact / 'original'}`",
    "",
    "Exit status: `0`",
    "",
    "Literal output:",
    "",
    "```json",
    baseline,
    "```",
    "",
    "## Modified behavior",
    "",
    f"Command: `python {artifact / 'behavior_probe.py'} {artifact / 'modified-snapshot'}`",
    "",
    "Exit status: `0`",
    "",
    "Literal output:",
    "",
    "```json",
    modified,
    "```",
    "",
    "## Automated validation",
    "",
    "| Command | Exit status | Literal result / full log |",
    "| --- | ---: | --- |",
]
summaries = {
    "root-fmt": "finished successfully",
    "root-check": "finished successfully",
    "root-test": "658 passed, 0 failed, 6 ignored",
    "gui-check": "finished successfully",
    "gui-test": "658 passed, 0 failed, 6 ignored",
    "gui-clippy": "finished successfully with -D warnings",
    "cli-check": "finished successfully",
    "cli-test": "427 passed, 0 failed, 6 ignored",
    "cli-clippy": "finished successfully with -D warnings",
    "tauri-fmt": "finished successfully",
    "tauri-check": "finished successfully",
    "tauri-test": "112 passed, 0 failed",
    "tauri-clippy": "4 pre-existing errors outside scoped history files",
    "frontend-typecheck": "tsc -b completed",
    "frontend-lint": "oxlint completed with 0 warnings and 0 errors",
    "frontend-test": "62 files passed; 212 tests passed",
    "frontend-build": "Vite built 3371 modules",
    "history-prettier": "all matched files use Prettier formatting",
    "i18n-parity": "1 passed, 0 failed",
    "diff-check": "no whitespace errors",
}
for row in results:
    command = row["command"].replace("|", "\\|")
    log = row["log"].replace("\\", "/")
    summary = summaries.get(row["name"], "see full log")
    lines.append(f"| `{command}` | `{row['exit_status']}` | `{summary}`; `{log}` |")

lines += [
    "",
    "The standalone Tauri Clippy result is nonzero only for:",
    "",
    "- `src-tauri/src/commands/empty_curtain.rs:402`",
    "- `src-tauri/src/commands/empty_curtain.rs:429`",
    "- `src-tauri/src/commands/settings.rs:431`",
    "- `src-tauri/src/contract/main_dps_detail.rs:101`",
    "",
    "No scoped history file appears in that diagnostic.",
    "",
    "CLI dependency command: `cargo tree -e normal --no-default-features --features cli`",
    "",
    "Literal result: `FORBIDDEN_GUI_DEPS=0` (tree stored in `cli-tree.txt`).",
    "",
    "## Patch application",
    "",
    f"Command: `git -C {artifact / 'validation/patch-apply-root'} apply --check --ignore-space-change --ignore-whitespace --whitespace=nowarn {artifact / 'history-parity.patch'}`",
    "",
    "Exit status: `0`",
    "",
    f"Command: `git -C {artifact / 'validation/patch-apply-root'} apply --ignore-space-change --ignore-whitespace --whitespace=nowarn {artifact / 'history-parity.patch'}`",
    "",
    "Exit status: `0`",
    "",
    "Literal output: `patch_logical_verified_files=13`",
    "",
    "## Rollback",
    "",
    f"Command: `& {artifact / 'rollback.ps1'} -Root {artifact / 'validation/rollback-root'}`",
    "",
    "Exit status: `0`",
    "",
    "Literal output: `rollback_verified_files=13`",
    "",
    f"Command: `python {artifact / 'verify_hashes.py'} {artifact / 'validation/rollback-root'} {artifact / 'original-hashes.json'}`",
    "",
    "Exit status: `0`",
    "",
    "Literal output: `verified_files=13`",
    "",
    "## Workspace artifact integrity",
    "",
    f"Command: `python {artifact / 'verify_hashes.py'} D:\\NTE_DPS_TOOL {artifact / 'modified-hashes.json'}`",
    "",
    "Exit status: `0`",
    "",
    "Literal output: `verified_files=13`",
    "",
]
(artifact / "verification.md").write_text("\n".join(lines), encoding="utf-8")
print(f"verification_lines={len(lines)}")
