param(
    [switch]$Check,
    [string]$OutputRoot
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputRoot) {
    $OutputRoot = $repoRoot
}
$schemaPath = Join-Path $repoRoot "res\mod-runtime-schema.json"
$schema = Get-Content -LiteralPath $schemaPath -Raw | ConvertFrom-Json

if ($schema.version -ne 1) {
    throw "Unsupported Mod runtime schema version: $($schema.version)"
}
if ($schema.capabilities.Count -eq 0 -or $schema.capabilities.Count -gt 16) {
    throw "Capability count is outside the u16 budget."
}

$names = @{}
$bits = @{}
$symbols = @{}
foreach ($capability in $schema.capabilities) {
    if ($capability.name -notmatch '^[a-z][a-z0-9.-]*$' -or
        $capability.symbol -notmatch '^[A-Z][A-Z0-9_]*$' -or
        $capability.bit -lt 0 -or $capability.bit -gt 15 -or
        $names.ContainsKey($capability.name) -or
        $bits.ContainsKey([int]$capability.bit) -or
        $symbols.ContainsKey($capability.symbol)) {
        throw "Invalid or duplicate capability entry: $($capability.name)"
    }
    $names[$capability.name] = $capability
    $bits[[int]$capability.bit] = $true
    $symbols[$capability.symbol] = $true
}

$serviceNames = @{}
$operations = @{}
foreach ($service in $schema.services) {
    if ($service.name -notmatch '^[a-z][a-z0-9._-]*$' -or
        $service.nativeService -notmatch '^[A-Z][A-Za-z0-9]*$' -or
        $service.operationSymbol -notmatch '^NTE_MODS_IPC_[A-Z0-9_]+$' -or
        $service.operation -lt 1 -or $service.operation -gt 65535 -or
        $serviceNames.ContainsKey($service.name) -or
        $operations.ContainsKey([int]$service.operation)) {
        throw "Invalid or duplicate service entry: $($service.name)"
    }
    foreach ($capabilityName in $service.capabilities) {
        if (-not $names.ContainsKey($capabilityName)) {
            throw "Unknown capability '$capabilityName' in service '$($service.name)'."
        }
    }
    $serviceNames[$service.name] = $true
    $operations[[int]$service.operation] = $true
}

function Capability-Constant([object]$capability) {
    "CAPABILITY_$($capability.symbol)"
}

$rust = @("// @generated by scripts/generate_mod_runtime_schema.ps1; do not edit.", "")
foreach ($capability in $schema.capabilities) {
    $rust += "const $(Capability-Constant $capability): u16 = 1 << $($capability.bit);"
}
$rust += ""
$rust += "#[rustfmt::skip]"
$rust += "const MOD_CAPABILITIES: &[(&str, u16)] = &["
foreach ($capability in $schema.capabilities) {
    $rust += "    (`"$($capability.name)`", $(Capability-Constant $capability)),"
}
$rust += "];"
$rust += ""
$rust += "#[rustfmt::skip]"
$rust += "const MOD_IPC_SERVICES: &[(&str, u16, u16)] = &["
foreach ($service in $schema.services) {
    $mask = ($service.capabilities | ForEach-Object {
        Capability-Constant $names[$_]
    }) -join " | "
    $rust += "    (`"$($service.name)`", $($service.operation), $mask),"
}
$rust += "];"
$rustText = ($rust -join "`n") + "`n"

$native = @(
    "// @generated by scripts/generate_mod_runtime_schema.ps1; do not edit.",
    "#pragma once",
    "",
    "#include <array>",
    "#include <cstdint>",
    "",
    "namespace nte::mods::runtime::schema",
    "{",
    "struct CapabilityEntry",
    "{",
    "    const char* name;",
    "    uint32_t mask;",
    "};",
    "",
    "struct ServiceEntry",
    "{",
    "    const char* name;",
    "    nte::mods::IpcKernelService service;",
    "    uint16_t operation;",
    "    uint32_t capability;",
    "};",
    "",
    "inline constexpr std::array<CapabilityEntry, $($schema.capabilities.Count)> CAPABILITIES{{"
)
foreach ($capability in $schema.capabilities) {
    $native += "    {`"$($capability.name)`", nte::mods::runtime::$(Capability-Constant $capability)},"
}
$native += "}};"
$native += ""
$native += "inline constexpr std::array<ServiceEntry, $($schema.services.Count)> SERVICES{{"
foreach ($service in $schema.services) {
    $mask = ($service.capabilities | ForEach-Object {
        "nte::mods::runtime::$(Capability-Constant $names[$_])"
    }) -join " | "
    $native += "    {`"$($service.name)`", nte::mods::IpcKernelService::$($service.nativeService), $($service.operation), $mask},"
}
$native += "}};"
$native += ""
foreach ($capability in $schema.capabilities) {
    $native += "static_assert(nte::mods::runtime::$(Capability-Constant $capability) == (uint32_t{1} << $($capability.bit)));"
}
$native += ""
foreach ($service in $schema.services) {
    $native += "static_assert(static_cast<uint16_t>($($service.operationSymbol)) == $($service.operation));"
}
$native += "} // namespace nte::mods::runtime::schema"
$nativeText = ($native -join "`n") + "`n"

$outputs = @{
    "src\storage\mod_runtime_schema.generated.rs" = $rustText
    "native\nte-mods-plugin\src\mod_runtime_schema.generated.hpp" = $nativeText
}
$utf8 = [System.Text.UTF8Encoding]::new($false)
function Normalize-GeneratedLineEndings([string]$Text) {
    return $Text.Replace("`r`n", "`n").Replace("`r", "`n")
}

foreach ($relative in $outputs.Keys) {
    $path = Join-Path $OutputRoot $relative
    if ($Check) {
        if (-not (Test-Path -LiteralPath $path)) {
            throw "Generated Mod runtime schema is stale: $relative"
        }
        $actual = Normalize-GeneratedLineEndings ([System.IO.File]::ReadAllText($path))
        $expected = Normalize-GeneratedLineEndings $outputs[$relative]
        if ($actual -cne $expected) {
            throw "Generated Mod runtime schema is stale: $relative"
        }
        continue
    }
    $parent = Split-Path -Parent $path
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
    [System.IO.File]::WriteAllText($path, $outputs[$relative], $utf8)
}

Write-Output "MOD-RUNTIME-SCHEMA: OK capabilities=$($schema.capabilities.Count) services=$($schema.services.Count) check=$Check"
